/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Admin 로그인 요청 DTO
 * @export
 * @interface AdminLoginRequest
 */
export interface AdminLoginRequest {
  /**
   * 관리자 ID
   * @type {string}
   * @memberof AdminLoginRequest
   */
  adminId: string
  /**
   * 관리자 비밀번호
   * @type {string}
   * @memberof AdminLoginRequest
   */
  password: string
}
