/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CategoryDto } from './category-dto'

/**
 * 주차장과 연계된 가게 정보 DTO
 * @export
 * @interface AssociatedStoreDto
 */
export interface AssociatedStoreDto {
  /**
   * 가게 ID
   * @type {number}
   * @memberof AssociatedStoreDto
   */
  storeId?: number
  /**
   * 가게 세부 카테고리 정보
   * @type {Array<CategoryDto>}
   * @memberof AssociatedStoreDto
   */
  categories?: Array<CategoryDto>
  /**
   * 가게 이름
   * @type {string}
   * @memberof AssociatedStoreDto
   */
  storeName?: string
  /**
   * 현재 가게 영업 여부 (true: 영업 중, false: 영업 종료, null: 정보 없음)
   * @type {boolean}
   * @memberof AssociatedStoreDto
   */
  isOpen?: boolean
}
