/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AssociatedStoreDto } from './associated-store-dto'

/**
 *
 * @export
 * @interface AssociatedParkingLotDto
 */
export interface AssociatedParkingLotDto {
  /**
   *
   * @type {string}
   * @memberof AssociatedParkingLotDto
   */
  parkingCode: string
  /**
   *
   * @type {string}
   * @memberof AssociatedParkingLotDto
   */
  name: string
  /**
   *
   * @type {boolean}
   * @memberof AssociatedParkingLotDto
   */
  isOpen?: boolean
  /**
   *
   * @type {number}
   * @memberof AssociatedParkingLotDto
   */
  hourlyFee?: number
  /**
   *
   * @type {number}
   * @memberof AssociatedParkingLotDto
   */
  capacity?: number
  /**
   *
   * @type {number}
   * @memberof AssociatedParkingLotDto
   */
  curCapacity?: number
  /**
   *
   * @type {Array<AssociatedStoreDto>}
   * @memberof AssociatedParkingLotDto
   */
  otherStores: Array<AssociatedStoreDto>
}
