/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DailyOperatingDto } from './daily-operating-dto'

/**
 * 점주에게 보여주는 연계된 주차장 정보 DTO
 * @export
 * @interface AssociatedParkingLotResponseDto
 */
export interface AssociatedParkingLotResponseDto {
  /**
   * 주차장 코드
   * @type {string}
   * @memberof AssociatedParkingLotResponseDto
   */
  parkingCode: string
  /**
   * 주차장 이름
   * @type {string}
   * @memberof AssociatedParkingLotResponseDto
   */
  name: string
  /**
   * 주소
   * @type {string}
   * @memberof AssociatedParkingLotResponseDto
   */
  address: string
  /**
   * 전화번호
   * @type {string}
   * @memberof AssociatedParkingLotResponseDto
   */
  tel?: string
  /**
   * 총 주차 가능 대수
   * @type {number}
   * @memberof AssociatedParkingLotResponseDto
   */
  capacity?: number
  /**
   * 운영 시간 정보
   * @type {Array<DailyOperatingDto>}
   * @memberof AssociatedParkingLotResponseDto
   */
  operatingHours?: Array<DailyOperatingDto>
  /**
   * 기본 요금
   * @type {number}
   * @memberof AssociatedParkingLotResponseDto
   */
  baseFee: number
  /**
   * 기본 시간(분)
   * @type {number}
   * @memberof AssociatedParkingLotResponseDto
   */
  baseTimeMin: number
  /**
   * 추가 요금
   * @type {number}
   * @memberof AssociatedParkingLotResponseDto
   */
  additionalFee?: number
  /**
   * 추가 시간(분)
   * @type {number}
   * @memberof AssociatedParkingLotResponseDto
   */
  additionalTimeMin?: number
  /**
   * 1일 최대 요금
   * @type {number}
   * @memberof AssociatedParkingLotResponseDto
   */
  dayPassFee?: number
}
