/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OperatingSlotDto } from './operating-slot-dto'

/**
 * 운영 시간 정보 (null 가능)
 * @export
 * @interface DailyOperatingDto
 */
export interface DailyOperatingDto {
  /**
   *
   * @type {string}
   * @memberof DailyOperatingDto
   */
  label: string
  /**
   *
   * @type {Array<OperatingSlotDto>}
   * @memberof DailyOperatingDto
   */
  slots: Array<OperatingSlotDto>
}
