/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface FeePolicyDto
 */
export interface FeePolicyDto {
  /**
   *
   * @type {number}
   * @memberof FeePolicyDto
   */
  baseFee?: number
  /**
   *
   * @type {number}
   * @memberof FeePolicyDto
   */
  baseTimeMin?: number
  /**
   *
   * @type {number}
   * @memberof FeePolicyDto
   */
  additionalFee?: number
  /**
   *
   * @type {number}
   * @memberof FeePolicyDto
   */
  additionalTimeMin?: number
  /**
   *
   * @type {number}
   * @memberof FeePolicyDto
   */
  dayPassFee?: number
  /**
   *
   * @type {number}
   * @memberof FeePolicyDto
   */
  monthlyPassFee?: number
}
