/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ParkingLotManualRequestDto } from './parking-lot-manual-request-dto'

/**
 * 주차장 연계 요청 DTO
 * @export
 * @interface LinkParkingRequestDto
 */
export interface LinkParkingRequestDto {
  /**
   * 연결할 기존 주차장의 코드 (새로운 주차장 등록시 null)
   * @type {string}
   * @memberof LinkParkingRequestDto
   */
  parkingCode?: string
  /**
   *
   * @type {ParkingLotManualRequestDto}
   * @memberof LinkParkingRequestDto
   */
  parkingLotInfo?: ParkingLotManualRequestDto
}
