/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface MyInfoResponseDto
 */
export interface MyInfoResponseDto {
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  nickname: string
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  provider: MyInfoResponseDtoProviderEnum
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  role: MyInfoResponseDtoRoleEnum
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  tel?: string
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  regionName?: string
  /**
   *
   * @type {string}
   * @memberof MyInfoResponseDto
   */
  vehicleNumber?: string
  /**
   *
   * @type {boolean}
   * @memberof MyInfoResponseDto
   */
  isOnboarding: boolean
  /**
   *
   * @type {boolean}
   * @memberof MyInfoResponseDto
   */
  isNotification: boolean
}

export const MyInfoResponseDtoProviderEnum = {
  Kakao: 'KAKAO',
  Apple: 'APPLE',
  None: 'NONE',
} as const

export type MyInfoResponseDtoProviderEnum =
  (typeof MyInfoResponseDtoProviderEnum)[keyof typeof MyInfoResponseDtoProviderEnum]
export const MyInfoResponseDtoRoleEnum = {
  Guest: 'GUEST',
  User: 'USER',
  Admin: 'ADMIN',
  Storekeeper: 'STOREKEEPER',
  Withdrawn: 'WITHDRAWN',
} as const

export type MyInfoResponseDtoRoleEnum = (typeof MyInfoResponseDtoRoleEnum)[keyof typeof MyInfoResponseDtoRoleEnum]
