/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ParkingBenefitDto } from './parking-benefit-dto'

/**
 *
 * @export
 * @interface MyStoreInfo
 */
export interface MyStoreInfo {
  /**
   *
   * @type {number}
   * @memberof MyStoreInfo
   */
  storeId: number
  /**
   *
   * @type {string}
   * @memberof MyStoreInfo
   */
  storeName: string
  /**
   *
   * @type {string}
   * @memberof MyStoreInfo
   */
  storeAddress: string
  /**
   *
   * @type {string}
   * @memberof MyStoreInfo
   */
  storePhone?: string
  /**
   *
   * @type {string}
   * @memberof MyStoreInfo
   */
  ownerName?: string
  /**
   *
   * @type {Array<ParkingBenefitDto>}
   * @memberof MyStoreInfo
   */
  parkingBenefits: Array<ParkingBenefitDto>
}
