/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ProductOrderItemDto } from './product-order-item-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { VisitorInfo } from './visitor-info'

/**
 *
 * @export
 * @interface OrderRequestDto
 */
export interface OrderRequestDto {
  /**
   *
   * @type {VisitorInfo}
   * @memberof OrderRequestDto
   */
  visitorInfo: VisitorInfo
  /**
   *
   * @type {Array<ProductOrderItemDto>}
   * @memberof OrderRequestDto
   */
  orderItems: Array<ProductOrderItemDto>
  /**
   *
   * @type {string}
   * @memberof OrderRequestDto
   */
  visitTime: string
  /**
   *
   * @type {number}
   * @memberof OrderRequestDto
   */
  clientTotalPrice: number
}
