/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ParkingBenefitDto } from './parking-benefit-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { ProductResponseDto } from './product-response-dto'

/**
 *
 * @export
 * @interface OrderFormResponseDto
 */
export interface OrderFormResponseDto {
  /**
   *
   * @type {number}
   * @memberof OrderFormResponseDto
   */
  storeId: number
  /**
   *
   * @type {string}
   * @memberof OrderFormResponseDto
   */
  storeName: string
  /**
   *
   * @type {Array<ParkingBenefitDto>}
   * @memberof OrderFormResponseDto
   */
  benefits: Array<ParkingBenefitDto>
  /**
   *
   * @type {Array<ProductResponseDto>}
   * @memberof OrderFormResponseDto
   */
  products: Array<ProductResponseDto>
}
