/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemInOrderDto } from './order-item-in-order-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { ParkingLotInfoInOrderDto } from './parking-lot-info-in-order-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { StoreInfoInOrderDto } from './store-info-in-order-dto'

/**
 *
 * @export
 * @interface OrderResponseDto
 */
export interface OrderResponseDto {
  /**
   *
   * @type {string}
   * @memberof OrderResponseDto
   */
  orderId: string
  /**
   *
   * @type {string}
   * @memberof OrderResponseDto
   */
  createdAt: string
  /**
   *
   * @type {string}
   * @memberof OrderResponseDto
   */
  visitorName: string
  /**
   *
   * @type {string}
   * @memberof OrderResponseDto
   */
  visitorTel: string
  /**
   *
   * @type {string}
   * @memberof OrderResponseDto
   */
  visitorRegionName: string
  /**
   *
   * @type {string}
   * @memberof OrderResponseDto
   */
  visitorVehicleNumber: string
  /**
   *
   * @type {string}
   * @memberof OrderResponseDto
   */
  visitTime: string
  /**
   *
   * @type {StoreInfoInOrderDto}
   * @memberof OrderResponseDto
   */
  storeInfo: StoreInfoInOrderDto
  /**
   *
   * @type {ParkingLotInfoInOrderDto}
   * @memberof OrderResponseDto
   */
  parkingLotInfo?: ParkingLotInfoInOrderDto
  /**
   *
   * @type {Array<OrderItemInOrderDto>}
   * @memberof OrderResponseDto
   */
  orderItems: Array<OrderItemInOrderDto>
  /**
   *
   * @type {number}
   * @memberof OrderResponseDto
   */
  totalPrice: number
  /**
   *
   * @type {number}
   * @memberof OrderResponseDto
   */
  totalDiscount: number
  /**
   *
   * @type {number}
   * @memberof OrderResponseDto
   */
  parkingDiscountMin: number
  /**
   *
   * @type {number}
   * @memberof OrderResponseDto
   */
  parkingFeeDiscount: number
}
