/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrderItemInOrderDto
 */
export interface OrderItemInOrderDto {
  /**
   *
   * @type {string}
   * @memberof OrderItemInOrderDto
   */
  productName: string
  /**
   *
   * @type {number}
   * @memberof OrderItemInOrderDto
   */
  quantity: number
  /**
   *
   * @type {number}
   * @memberof OrderItemInOrderDto
   */
  price: number
}
