/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PagingInfo } from './paging-info'
// May contain unused imports in some cases
// @ts-ignore
import type { ParkingLotListResponse } from './parking-lot-list-response'

/**
 *
 * @export
 * @interface PageSearchResponseParkingLotListResponse
 */
export interface PageSearchResponseParkingLotListResponse {
  /**
   *
   * @type {Array<ParkingLotListResponse>}
   * @memberof PageSearchResponseParkingLotListResponse
   */
  content: Array<ParkingLotListResponse>
  /**
   *
   * @type {PagingInfo}
   * @memberof PageSearchResponseParkingLotListResponse
   */
  paging: PagingInfo
  /**
   *
   * @type {number}
   * @memberof PageSearchResponseParkingLotListResponse
   */
  searchRadiusKm?: number
}
