/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ParkingStatusResponseDto
 */
export interface ParkingStatusResponseDto {
  /**
   *
   * @type {string}
   * @memberof ParkingStatusResponseDto
   */
  orderId: string
  /**
   *
   * @type {string}
   * @memberof ParkingStatusResponseDto
   */
  visitTime?: string
  /**
   *
   * @type {string}
   * @memberof ParkingStatusResponseDto
   */
  freeParkingUntil?: string
  /**
   *
   * @type {number}
   * @memberof ParkingStatusResponseDto
   */
  extraCharge: number
  /**
   *
   * @type {number}
   * @memberof ParkingStatusResponseDto
   */
  parkingFeeDiscount: number
  /**
   *
   * @type {string}
   * @memberof ParkingStatusResponseDto
   */
  parkingLotName: string
  /**
   *
   * @type {string}
   * @memberof ParkingStatusResponseDto
   */
  parkingLotTodayClosingTime?: string
  /**
   *
   * @type {string}
   * @memberof ParkingStatusResponseDto
   */
  parkingLotAddress?: string
  /**
   *
   * @type {number}
   * @memberof ParkingStatusResponseDto
   */
  baseTimeMin?: number
  /**
   *
   * @type {number}
   * @memberof ParkingStatusResponseDto
   */
  baseFee?: number
  /**
   *
   * @type {number}
   * @memberof ParkingStatusResponseDto
   */
  additionalTimeMin?: number
  /**
   *
   * @type {number}
   * @memberof ParkingStatusResponseDto
   */
  additionalFee?: number
}
