/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ParkingLotListResponse
 */
export interface ParkingLotListResponse {
  /**
   *
   * @type {string}
   * @memberof ParkingLotListResponse
   */
  parkingCode: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotListResponse
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotListResponse
   */
  address?: string
  /**
   *
   * @type {number}
   * @memberof ParkingLotListResponse
   */
  capacity?: number
  /**
   *
   * @type {boolean}
   * @memberof ParkingLotListResponse
   */
  isRealtime?: boolean
  /**
   *
   * @type {number}
   * @memberof ParkingLotListResponse
   */
  curCapacity?: number
  /**
   *
   * @type {number}
   * @memberof ParkingLotListResponse
   */
  baseFee?: number
  /**
   *
   * @type {number}
   * @memberof ParkingLotListResponse
   */
  baseTimeMin?: number
  /**
   *
   * @type {number}
   * @memberof ParkingLotListResponse
   */
  lat: number
  /**
   *
   * @type {number}
   * @memberof ParkingLotListResponse
   */
  lon: number
  /**
   *
   * @type {boolean}
   * @memberof ParkingLotListResponse
   */
  isOpen?: boolean
  /**
   *
   * @type {string}
   * @memberof ParkingLotListResponse
   */
  congestion?: string
}
