/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 텍스트 기반 주차장 검색 요청 DTO
 * @export
 * @interface ParkingLotTextSearchRequest
 */
export interface ParkingLotTextSearchRequest {
  /**
   * 현재 위치 위도
   * @type {number}
   * @memberof ParkingLotTextSearchRequest
   */
  lat?: number
  /**
   * 현재 위치 경도
   * @type {number}
   * @memberof ParkingLotTextSearchRequest
   */
  lon?: number
  /**
   * 검색어
   * @type {string}
   * @memberof ParkingLotTextSearchRequest
   */
  query: string
  /**
   * 페이지 번호 (0부터 시작)
   * @type {number}
   * @memberof ParkingLotTextSearchRequest
   */
  page: number
}
