/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ParkingLotInfoInOrderDto
 */
export interface ParkingLotInfoInOrderDto {
  /**
   *
   * @type {string}
   * @memberof ParkingLotInfoInOrderDto
   */
  parkingLotId: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotInfoInOrderDto
   */
  parkingLotName: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotInfoInOrderDto
   */
  parkingLotAddress?: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotInfoInOrderDto
   */
  parkingLotTodayClosingTime?: string
}
