/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 주차 혜택 추가/수정 요청 DTO
 * @export
 * @interface ParkingBenefitRequestDto
 */
export interface ParkingBenefitRequestDto {
  /**
   * 혜택 적용을 위한 최소 구매 금액
   * @type {number}
   * @memberof ParkingBenefitRequestDto
   */
  purchaseAmount: number
  /**
   * 제공되는 무료 주차 시간(분)
   * @type {number}
   * @memberof ParkingBenefitRequestDto
   */
  discountMin: number
}
