/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AssociatedStoreDto } from './associated-store-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { FeePolicyDto } from './fee-policy-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { GroupedOperatingHoursDto } from './grouped-operating-hours-dto'

/**
 *
 * @export
 * @interface ParkingLotDetailResponse
 */
export interface ParkingLotDetailResponse {
  /**
   *
   * @type {string}
   * @memberof ParkingLotDetailResponse
   */
  parkingCode: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotDetailResponse
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotDetailResponse
   */
  address?: string
  /**
   *
   * @type {boolean}
   * @memberof ParkingLotDetailResponse
   */
  isOpen?: boolean
  /**
   *
   * @type {number}
   * @memberof ParkingLotDetailResponse
   */
  capacity?: number
  /**
   *
   * @type {number}
   * @memberof ParkingLotDetailResponse
   */
  curCapacity?: number
  /**
   *
   * @type {string}
   * @memberof ParkingLotDetailResponse
   */
  congestion?: string
  /**
   *
   * @type {string}
   * @memberof ParkingLotDetailResponse
   */
  todayClosingTime?: string
  /**
   *
   * @type {boolean}
   * @memberof ParkingLotDetailResponse
   */
  isRealtime: boolean
  /**
   *
   * @type {string}
   * @memberof ParkingLotDetailResponse
   */
  tel?: string
  /**
   *
   * @type {boolean}
   * @memberof ParkingLotDetailResponse
   */
  isFree: boolean
  /**
   *
   * @type {number}
   * @memberof ParkingLotDetailResponse
   */
  lat?: number
  /**
   *
   * @type {number}
   * @memberof ParkingLotDetailResponse
   */
  lon?: number
  /**
   *
   * @type {FeePolicyDto}
   * @memberof ParkingLotDetailResponse
   */
  feePolicy: FeePolicyDto
  /**
   *
   * @type {Array<GroupedOperatingHoursDto>}
   * @memberof ParkingLotDetailResponse
   */
  operatingTable: Array<GroupedOperatingHoursDto>
  /**
   *
   * @type {Array<AssociatedStoreDto>}
   * @memberof ParkingLotDetailResponse
   */
  associatedStores: Array<AssociatedStoreDto>
}
