/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 지도 기반 주차장 검색 요청 DTO
 * @export
 * @interface ParkingLotSearchRequest
 */
export interface ParkingLotSearchRequest {
  /**
   * 검색 반경 레벨 (1: 2km, 2: 4km)
   * @type {number}
   * @memberof ParkingLotSearchRequest
   */
  distanceLevel: number
  /**
   * 위도
   * @type {number}
   * @memberof ParkingLotSearchRequest
   */
  lat?: number
  /**
   * 경도
   * @type {number}
   * @memberof ParkingLotSearchRequest
   */
  lon?: number
  /**
   * 검색어 (텍스트 검색 시 사용)
   * @type {string}
   * @memberof ParkingLotSearchRequest
   */
  query?: string
  /**
   * 검색 정렬 (예: DISTANCE, PRICE)
   * @type {string}
   * @memberof ParkingLotSearchRequest
   */
  sort?: ParkingLotSearchRequestSortEnum
  /**
   * 무료 여부
   * @type {boolean}
   * @memberof ParkingLotSearchRequest
   */
  isFree?: boolean
  /**
   * 실시간 주차 가능 여부
   * @type {boolean}
   * @memberof ParkingLotSearchRequest
   */
  isRealtime?: boolean
  /**
   * 주차장 혼잡도 (예: 여유, 보통, 혼잡)
   * @type {Array<string>}
   * @memberof ParkingLotSearchRequest
   */
  congestion?: Array<string>
  /**
   * 최대 시간당 요금 (단위: 원)
   * @type {number}
   * @memberof ParkingLotSearchRequest
   */
  maxFeePerHour?: number
  /**
   * 운영 여부
   * @type {boolean}
   * @memberof ParkingLotSearchRequest
   */
  isOpen?: boolean
  /**
   * 24시간 운영 여부
   * @type {boolean}
   * @memberof ParkingLotSearchRequest
   */
  is24Hours?: boolean
  /**
   * 확인할 요일 (대문자, 예: MONDAY)
   * @type {string}
   * @memberof ParkingLotSearchRequest
   */
  checkDayOfWeek?: string
  /**
   * 확인할 시간 (HHmm 형식, 예: 1430)
   * @type {string}
   * @memberof ParkingLotSearchRequest
   */
  checkTime?: string
  /**
   * 페이지 번호 (0부터 시작)
   * @type {number}
   * @memberof ParkingLotSearchRequest
   */
  page: number
}

export const ParkingLotSearchRequestSortEnum = {
  Distance: 'DISTANCE',
  Price: 'PRICE',
} as const

export type ParkingLotSearchRequestSortEnum =
  (typeof ParkingLotSearchRequestSortEnum)[keyof typeof ParkingLotSearchRequestSortEnum]
