/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PresignedUrlResponse
 */
export interface PresignedUrlResponse {
  /**
   *
   * @type {string}
   * @memberof PresignedUrlResponse
   */
  presignedUrl: string
  /**
   *
   * @type {string}
   * @memberof PresignedUrlResponse
   */
  imageKey: string
}
