/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RecentSearchResponse
 */
export interface RecentSearchResponse {
  /**
   *
   * @type {number}
   * @memberof RecentSearchResponse
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof RecentSearchResponse
   */
  query: string
  /**
   *
   * @type {string}
   * @memberof RecentSearchResponse
   */
  date: string
}
