/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { StoreDetailResponse } from './store-detail-response'

/**
 *
 * @export
 * @interface ResponseDtoStoreDetailResponse
 */
export interface ResponseDtoStoreDetailResponse {
  /**
   *
   * @type {string}
   * @memberof ResponseDtoStoreDetailResponse
   */
  message: string
  /**
   *
   * @type {StoreDetailResponse}
   * @memberof ResponseDtoStoreDetailResponse
   */
  data?: StoreDetailResponse
}
