/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AssociatedParkingLotResponseDto } from './associated-parking-lot-response-dto'

/**
 *
 * @export
 * @interface ResponseDtoListAssociatedParkingLotResponseDto
 */
export interface ResponseDtoListAssociatedParkingLotResponseDto {
  /**
   *
   * @type {string}
   * @memberof ResponseDtoListAssociatedParkingLotResponseDto
   */
  message: string
  /**
   *
   * @type {Array<AssociatedParkingLotResponseDto>}
   * @memberof ResponseDtoListAssociatedParkingLotResponseDto
   */
  data?: Array<AssociatedParkingLotResponseDto>
}
