/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ProductResponseDto } from './product-response-dto'

/**
 *
 * @export
 * @interface ResponseDtoProductResponseDto
 */
export interface ResponseDtoProductResponseDto {
  /**
   *
   * @type {string}
   * @memberof ResponseDtoProductResponseDto
   */
  message: string
  /**
   *
   * @type {ProductResponseDto}
   * @memberof ResponseDtoProductResponseDto
   */
  data?: ProductResponseDto
}
