/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UserInfoResponse } from './user-info-response'

/**
 *
 * @export
 * @interface ResponseDtoUserInfoResponse
 */
export interface ResponseDtoUserInfoResponse {
  /**
   *
   * @type {string}
   * @memberof ResponseDtoUserInfoResponse
   */
  message: string
  /**
   *
   * @type {UserInfoResponse}
   * @memberof ResponseDtoUserInfoResponse
   */
  data?: UserInfoResponse
}
