/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ResponseDtoUnit
 */
export interface ResponseDtoUnit {
  /**
   *
   * @type {string}
   * @memberof ResponseDtoUnit
   */
  message: string
  /**
   *
   * @type {object}
   * @memberof ResponseDtoUnit
   */
  data?: object
}
