/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SearchItemResponse
 */
export interface SearchItemResponse {
  /**
   *
   * @type {string}
   * @memberof SearchItemResponse
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof SearchItemResponse
   */
  roadAddress: string
  /**
   *
   * @type {number}
   * @memberof SearchItemResponse
   */
  lat: number
  /**
   *
   * @type {number}
   * @memberof SearchItemResponse
   */
  lon: number
}
