/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AgreementDto } from './agreement-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { ParkingLotManualRequestDto } from './parking-lot-manual-request-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { StoreManualRequestDto } from './store-manual-request-dto'

/**
 * 점주 회원가입 요청 DTO
 * @export
 * @interface StorekeeperRegisterRequest
 */
export interface StorekeeperRegisterRequest {
  /**
   * 점주가 동의한 약관 목록
   * @type {Array<AgreementDto>}
   * @memberof StorekeeperRegisterRequest
   */
  agreements: Array<AgreementDto>
  /**
   * 점주 아이디
   * @type {string}
   * @memberof StorekeeperRegisterRequest
   */
  adminId: string
  /**
   * 점주 비밀번호
   * @type {string}
   * @memberof StorekeeperRegisterRequest
   */
  password: string
  /**
   * 점주 이메일
   * @type {string}
   * @memberof StorekeeperRegisterRequest
   */
  email: string
  /**
   * 사업자번호
   * @type {string}
   * @memberof StorekeeperRegisterRequest
   */
  businessNumber: string
  /**
   * 가게 ID (신규 등록 시에는 null)
   * @type {number}
   * @memberof StorekeeperRegisterRequest
   */
  storeId?: number
  /**
   *
   * @type {StoreManualRequestDto}
   * @memberof StorekeeperRegisterRequest
   */
  storeInfo?: StoreManualRequestDto
  /**
   * 선택된 기존 주차장 코드 (신규 등록 시에는 null)
   * @type {string}
   * @memberof StorekeeperRegisterRequest
   */
  parkingCode?: string
  /**
   *
   * @type {ParkingLotManualRequestDto}
   * @memberof StorekeeperRegisterRequest
   */
  parkingLotInfo?: ParkingLotManualRequestDto
}
