/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 지도 기반 가게 검색 요청 DTO
 * @export
 * @interface StoreSearchRequest
 */
export interface StoreSearchRequest {
  /**
   * 위도
   * @type {number}
   * @memberof StoreSearchRequest
   */
  lat?: number
  /**
   * 경도
   * @type {number}
   * @memberof StoreSearchRequest
   */
  lon?: number
  /**
   * 카테고리 ID
   * @type {number}
   * @memberof StoreSearchRequest
   */
  categoryId?: number
  /**
   * 검색 정렬 (예: DISTANCE)
   * @type {string}
   * @memberof StoreSearchRequest
   */
  sort: StoreSearchRequestSortEnum
  /**
   * 최대 무료 주차(분)
   * @type {number}
   * @memberof StoreSearchRequest
   */
  maxFreeMin?: number
  /**
   * 운영 여부
   * @type {boolean}
   * @memberof StoreSearchRequest
   */
  isOpen?: boolean
  /**
   * 24시간 운영 여부
   * @type {boolean}
   * @memberof StoreSearchRequest
   */
  is24Hours?: boolean
  /**
   * 확인할 요일 (대문자, 예: MONDAY)
   * @type {string}
   * @memberof StoreSearchRequest
   */
  checkDayOfWeek?: string
  /**
   * 확인할 시간 (HHmm 형식, 예: 1430)
   * @type {string}
   * @memberof StoreSearchRequest
   */
  checkTime?: string
  /**
   * 페이지 번호 (0부터 시작)
   * @type {number}
   * @memberof StoreSearchRequest
   */
  page: number
}

export const StoreSearchRequestSortEnum = {
  Distance: 'DISTANCE',
  Price: 'PRICE',
} as const

export type StoreSearchRequestSortEnum = (typeof StoreSearchRequestSortEnum)[keyof typeof StoreSearchRequestSortEnum]
