/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StoreSimpleResponse
 */
export interface StoreSimpleResponse {
  /**
   *
   * @type {number}
   * @memberof StoreSimpleResponse
   */
  storeId: number
  /**
   *
   * @type {string}
   * @memberof StoreSimpleResponse
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof StoreSimpleResponse
   */
  address?: string
}
