/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StoreListResponse
 */
export interface StoreListResponse {
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  storeId: number
  /**
   *
   * @type {string}
   * @memberof StoreListResponse
   */
  name: string
  /**
   *
   * @type {Array<string>}
   * @memberof StoreListResponse
   */
  categoryNames: Array<string>
  /**
   *
   * @type {string}
   * @memberof StoreListResponse
   */
  address?: string
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  lat: number
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  lon: number
  /**
   *
   * @type {boolean}
   * @memberof StoreListResponse
   */
  isOpen?: boolean
  /**
   *
   * @type {boolean}
   * @memberof StoreListResponse
   */
  isCoalition: boolean
}
