/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CategoryDto } from './category-dto'

/**
 *
 * @export
 * @interface StoreListResponse
 */
export interface StoreListResponse {
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  storeId: number
  /**
   *
   * @type {string}
   * @memberof StoreListResponse
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof StoreListResponse
   */
  address: string
  /**
   *
   * @type {string}
   * @memberof StoreListResponse
   */
  storeType?: string
  /**
   *
   * @type {Array<CategoryDto>}
   * @memberof StoreListResponse
   */
  categories?: Array<CategoryDto>
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  lat: number
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  lon: number
  /**
   *
   * @type {boolean}
   * @memberof StoreListResponse
   */
  isOpen?: boolean
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  purchaseAmount?: number
  /**
   *
   * @type {number}
   * @memberof StoreListResponse
   */
  discountMin?: number
}
