/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface StoreOwnershipReqResponse
 */
export interface StoreOwnershipReqResponse {
  /**
   *
   * @type {number}
   * @memberof StoreOwnershipReqResponse
   */
  requestId: number
  /**
   *
   * @type {number}
   * @memberof StoreOwnershipReqResponse
   */
  storeId: number
  /**
   *
   * @type {number}
   * @memberof StoreOwnershipReqResponse
   */
  userId: number
  /**
   *
   * @type {string}
   * @memberof StoreOwnershipReqResponse
   */
  status: string
  /**
   *
   * @type {string}
   * @memberof StoreOwnershipReqResponse
   */
  storeName: string
  /**
   *
   * @type {string}
   * @memberof StoreOwnershipReqResponse
   */
  userName: string
}
