/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DailyOperatingDto } from './daily-operating-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { StoreAddressDto } from './store-address-dto'

/**
 * 점주가 수동으로 입력하는 가게 정보 DTO
 * @export
 * @interface StoreManualRequestDto
 */
export interface StoreManualRequestDto {
  /**
   * 가게 이름
   * @type {string}
   * @memberof StoreManualRequestDto
   */
  storeName: string
  /**
   *
   * @type {StoreAddressDto}
   * @memberof StoreManualRequestDto
   */
  storeAddress: StoreAddressDto
  /**
   * 전화번호
   * @type {string}
   * @memberof StoreManualRequestDto
   */
  tel?: string
  /**
   * 가게 카테고리 ID
   * @type {number}
   * @memberof StoreManualRequestDto
   */
  categoryId: number
  /**
   * 운영 시간 정보 (null 가능)
   * @type {Array<DailyOperatingDto>}
   * @memberof StoreManualRequestDto
   */
  operatingHours?: Array<DailyOperatingDto>
}
