/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AssociatedParkingLotDto } from './associated-parking-lot-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { DailyOperatingDto } from './daily-operating-dto'

/**
 *
 * @export
 * @interface StoreDetailResponse
 */
export interface StoreDetailResponse {
  /**
   *
   * @type {number}
   * @memberof StoreDetailResponse
   */
  storeId: number
  /**
   *
   * @type {string}
   * @memberof StoreDetailResponse
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof StoreDetailResponse
   */
  storeType?: StoreDetailResponseStoreTypeEnum
  /**
   *
   * @type {Array<string>}
   * @memberof StoreDetailResponse
   */
  categoryNames?: Array<string>
  /**
   *
   * @type {string}
   * @memberof StoreDetailResponse
   */
  address?: string
  /**
   *
   * @type {boolean}
   * @memberof StoreDetailResponse
   */
  isOpen?: boolean
  /**
   *
   * @type {string}
   * @memberof StoreDetailResponse
   */
  todayClosingTime?: string
  /**
   *
   * @type {string}
   * @memberof StoreDetailResponse
   */
  tel?: string
  /**
   *
   * @type {number}
   * @memberof StoreDetailResponse
   */
  lat: number
  /**
   *
   * @type {number}
   * @memberof StoreDetailResponse
   */
  lon: number
  /**
   *
   * @type {number}
   * @memberof StoreDetailResponse
   */
  maxFreeMin?: number
  /**
   *
   * @type {Array<DailyOperatingDto>}
   * @memberof StoreDetailResponse
   */
  operatingTable: Array<DailyOperatingDto>
  /**
   *
   * @type {Array<AssociatedParkingLotDto>}
   * @memberof StoreDetailResponse
   */
  associatedParkingLots: Array<AssociatedParkingLotDto>
}

export const StoreDetailResponseStoreTypeEnum = {
  General: 'GENERAL',
  ProductDetail: 'PRODUCT_DETAIL',
  Coalition: 'COALITION',
} as const

export type StoreDetailResponseStoreTypeEnum =
  (typeof StoreDetailResponseStoreTypeEnum)[keyof typeof StoreDetailResponseStoreTypeEnum]
