/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TermDto
 */
export interface TermDto {
  /**
   *
   * @type {number}
   * @memberof TermDto
   */
  termId: number
  /**
   *
   * @type {string}
   * @memberof TermDto
   */
  version?: string
  /**
   *
   * @type {string}
   * @memberof TermDto
   */
  title?: string
  /**
   *
   * @type {string}
   * @memberof TermDto
   */
  content?: string
  /**
   *
   * @type {boolean}
   * @memberof TermDto
   */
  mandatory: boolean
  /**
   *
   * @type {string}
   * @memberof TermDto
   */
  effectiveDate: string
}
