/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
  /**
   *
   * @type {string}
   * @memberof UserResponse
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof UserResponse
   */
  nickname: string
  /**
   *
   * @type {string}
   * @memberof UserResponse
   */
  provider: UserResponseProviderEnum
  /**
   *
   * @type {string}
   * @memberof UserResponse
   */
  role: UserResponseRoleEnum
}

export const UserResponseProviderEnum = {
  Kakao: 'KAKAO',
  Apple: 'APPLE',
  None: 'NONE',
} as const

export type UserResponseProviderEnum = (typeof UserResponseProviderEnum)[keyof typeof UserResponseProviderEnum]
export const UserResponseRoleEnum = {
  Guest: 'GUEST',
  User: 'USER',
  Admin: 'ADMIN',
} as const

export type UserResponseRoleEnum = (typeof UserResponseRoleEnum)[keyof typeof UserResponseRoleEnum]
