/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface VisitorInfo
 */
export interface VisitorInfo {
  /**
   * 방문자 이름
   * @type {string}
   * @memberof VisitorInfo
   */
  name?: string
  /**
   * 방문자 전화번호
   * @type {string}
   * @memberof VisitorInfo
   */
  tel?: string
  /**
   * 방문자 지역명
   * @type {string}
   * @memberof VisitorInfo
   */
  regionName?: string
  /**
   * 방문자 차량번호
   * @type {string}
   * @memberof VisitorInfo
   */
  vehicleNumber?: string
}
