/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { AdminLoginRequest } from '../models'
// @ts-ignore
import type { ResponseDtoListStorekeeperRequestResponse } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
// @ts-ignore
import type { TokenResponse } from '../models'
/**
 * AdminApi - axios parameter creator
 * @export
 */
export const AdminApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 관리자가 특정 가입 신청을 승인 처리합니다.
     * @summary 점주 가입 신청 승인
     * @param {string} adminId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    approveStorekeeperRequest: async (adminId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'adminId' is not null or undefined
      assertParamExists('approveStorekeeperRequest', 'adminId', adminId)
      const localVarPath = `/admin/storekeeper-requests/{adminId}/approve`.replace(
        `{${'adminId'}}`,
        encodeURIComponent(String(adminId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 관리자가 상태(PENDING, APPROVED, REJECTED)에 따라 가입 신청 목록을 조회합니다.
     * @summary 점주 가입 신청 목록 조회
     * @param {GetStorekeeperRequestsStatusEnum} status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStorekeeperRequests: async (
      status: GetStorekeeperRequestsStatusEnum,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'status' is not null or undefined
      assertParamExists('getStorekeeperRequests', 'status', status)
      const localVarPath = `/admin/storekeeper-requests`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (status !== undefined) {
        localVarQueryParameter['status'] = status
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 관리자가 로그인하는 API입니다.
     * @summary 관리자 로그인
     * @param {AdminLoginRequest} adminLoginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login1: async (adminLoginRequest: AdminLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'adminLoginRequest' is not null or undefined
      assertParamExists('login1', 'adminLoginRequest', adminLoginRequest)
      const localVarPath = `/admin/auth/login`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(adminLoginRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 관리자가 특정 가입 신청을 거절 처리합니다.
     * @summary 점주 가입 신청 거절
     * @param {string} adminId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rejectStorekeeperRequest: async (adminId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'adminId' is not null or undefined
      assertParamExists('rejectStorekeeperRequest', 'adminId', adminId)
      const localVarPath = `/admin/storekeeper-requests/{adminId}/reject`.replace(
        `{${'adminId'}}`,
        encodeURIComponent(String(adminId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * AdminApi - functional programming interface
 * @export
 */
export const AdminApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AdminApiAxiosParamCreator(configuration)
  return {
    /**
     * 관리자가 특정 가입 신청을 승인 처리합니다.
     * @summary 점주 가입 신청 승인
     * @param {string} adminId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async approveStorekeeperRequest(
      adminId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.approveStorekeeperRequest(adminId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.approveStorekeeperRequest']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 관리자가 상태(PENDING, APPROVED, REJECTED)에 따라 가입 신청 목록을 조회합니다.
     * @summary 점주 가입 신청 목록 조회
     * @param {GetStorekeeperRequestsStatusEnum} status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getStorekeeperRequests(
      status: GetStorekeeperRequestsStatusEnum,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListStorekeeperRequestResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getStorekeeperRequests(status, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.getStorekeeperRequests']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 관리자가 로그인하는 API입니다.
     * @summary 관리자 로그인
     * @param {AdminLoginRequest} adminLoginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async login1(
      adminLoginRequest: AdminLoginRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TokenResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.login1(adminLoginRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath = operationServerMap['AdminApi.login1']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 관리자가 특정 가입 신청을 거절 처리합니다.
     * @summary 점주 가입 신청 거절
     * @param {string} adminId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rejectStorekeeperRequest(
      adminId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rejectStorekeeperRequest(adminId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AdminApi.rejectStorekeeperRequest']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * AdminApi - factory interface
 * @export
 */
export const AdminApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = AdminApiFp(configuration)
  return {
    /**
     * 관리자가 특정 가입 신청을 승인 처리합니다.
     * @summary 점주 가입 신청 승인
     * @param {AdminApiApproveStorekeeperRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    approveStorekeeperRequest(
      requestParameters: AdminApiApproveStorekeeperRequestRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .approveStorekeeperRequest(requestParameters.adminId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 관리자가 상태(PENDING, APPROVED, REJECTED)에 따라 가입 신청 목록을 조회합니다.
     * @summary 점주 가입 신청 목록 조회
     * @param {AdminApiGetStorekeeperRequestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getStorekeeperRequests(
      requestParameters: AdminApiGetStorekeeperRequestsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoListStorekeeperRequestResponse> {
      return localVarFp
        .getStorekeeperRequests(requestParameters.status, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 관리자가 로그인하는 API입니다.
     * @summary 관리자 로그인
     * @param {AdminApiLogin1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login1(requestParameters: AdminApiLogin1Request, options?: RawAxiosRequestConfig): AxiosPromise<TokenResponse> {
      return localVarFp.login1(requestParameters.adminLoginRequest, options).then((request) => request(axios, basePath))
    },
    /**
     * 관리자가 특정 가입 신청을 거절 처리합니다.
     * @summary 점주 가입 신청 거절
     * @param {AdminApiRejectStorekeeperRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rejectStorekeeperRequest(
      requestParameters: AdminApiRejectStorekeeperRequestRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .rejectStorekeeperRequest(requestParameters.adminId, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for approveStorekeeperRequest operation in AdminApi.
 * @export
 * @interface AdminApiApproveStorekeeperRequestRequest
 */
export interface AdminApiApproveStorekeeperRequestRequest {
  /**
   *
   * @type {string}
   * @memberof AdminApiApproveStorekeeperRequest
   */
  readonly adminId: string
}

/**
 * Request parameters for getStorekeeperRequests operation in AdminApi.
 * @export
 * @interface AdminApiGetStorekeeperRequestsRequest
 */
export interface AdminApiGetStorekeeperRequestsRequest {
  /**
   *
   * @type {'PENDING' | 'APPROVED' | 'REJECTED'}
   * @memberof AdminApiGetStorekeeperRequests
   */
  readonly status: GetStorekeeperRequestsStatusEnum
}

/**
 * Request parameters for login1 operation in AdminApi.
 * @export
 * @interface AdminApiLogin1Request
 */
export interface AdminApiLogin1Request {
  /**
   *
   * @type {AdminLoginRequest}
   * @memberof AdminApiLogin1
   */
  readonly adminLoginRequest: AdminLoginRequest
}

/**
 * Request parameters for rejectStorekeeperRequest operation in AdminApi.
 * @export
 * @interface AdminApiRejectStorekeeperRequestRequest
 */
export interface AdminApiRejectStorekeeperRequestRequest {
  /**
   *
   * @type {string}
   * @memberof AdminApiRejectStorekeeperRequest
   */
  readonly adminId: string
}

/**
 * AdminApi - object-oriented interface
 * @export
 * @class AdminApi
 * @extends {BaseAPI}
 */
export class AdminApi extends BaseAPI {
  /**
   * 관리자가 특정 가입 신청을 승인 처리합니다.
   * @summary 점주 가입 신청 승인
   * @param {AdminApiApproveStorekeeperRequestRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApi
   */
  public approveStorekeeperRequest(
    requestParameters: AdminApiApproveStorekeeperRequestRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AdminApiFp(this.configuration)
      .approveStorekeeperRequest(requestParameters.adminId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 관리자가 상태(PENDING, APPROVED, REJECTED)에 따라 가입 신청 목록을 조회합니다.
   * @summary 점주 가입 신청 목록 조회
   * @param {AdminApiGetStorekeeperRequestsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApi
   */
  public getStorekeeperRequests(
    requestParameters: AdminApiGetStorekeeperRequestsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AdminApiFp(this.configuration)
      .getStorekeeperRequests(requestParameters.status, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 관리자가 로그인하는 API입니다.
   * @summary 관리자 로그인
   * @param {AdminApiLogin1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApi
   */
  public login1(requestParameters: AdminApiLogin1Request, options?: RawAxiosRequestConfig) {
    return AdminApiFp(this.configuration)
      .login1(requestParameters.adminLoginRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 관리자가 특정 가입 신청을 거절 처리합니다.
   * @summary 점주 가입 신청 거절
   * @param {AdminApiRejectStorekeeperRequestRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AdminApi
   */
  public rejectStorekeeperRequest(
    requestParameters: AdminApiRejectStorekeeperRequestRequest,
    options?: RawAxiosRequestConfig
  ) {
    return AdminApiFp(this.configuration)
      .rejectStorekeeperRequest(requestParameters.adminId, options)
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * @export
 */
export const GetStorekeeperRequestsStatusEnum = {
  Pending: 'PENDING',
  Approved: 'APPROVED',
  Rejected: 'REJECTED',
} as const
export type GetStorekeeperRequestsStatusEnum =
  (typeof GetStorekeeperRequestsStatusEnum)[keyof typeof GetStorekeeperRequestsStatusEnum]
