/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { AppleLoginRequest } from '../models'
// @ts-ignore
import type { ResponseDtoTokenResponse } from '../models'
// @ts-ignore
import type { TokenRequest } from '../models'
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 애플 앱 소셜 로그인을 위한 API입니다.
     * @summary 애플 앱 소셜 로그인
     * @param {AppleLoginRequest} appleLoginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apple: async (appleLoginRequest: AppleLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'appleLoginRequest' is not null or undefined
      assertParamExists('apple', 'appleLoginRequest', appleLoginRequest)
      const localVarPath = `/auth/login/apple`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(appleLoginRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 카카오 앱 소셜 로그인을 위한 API입니다.
     * @summary 카카오 앱 소셜 로그인
     * @param {TokenRequest} tokenRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    kakao: async (tokenRequest: TokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'tokenRequest' is not null or undefined
      assertParamExists('kakao', 'tokenRequest', tokenRequest)
      const localVarPath = `/auth/login/kakao`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(tokenRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Access Token을 갱신하는 API입니다.
     * @summary Access Token 갱신
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reissueRefreshToken: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/auth/refresh`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
  return {
    /**
     * 애플 앱 소셜 로그인을 위한 API입니다.
     * @summary 애플 앱 소셜 로그인
     * @param {AppleLoginRequest} appleLoginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async apple(
      appleLoginRequest: AppleLoginRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoTokenResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.apple(appleLoginRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath = operationServerMap['AuthApi.apple']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 카카오 앱 소셜 로그인을 위한 API입니다.
     * @summary 카카오 앱 소셜 로그인
     * @param {TokenRequest} tokenRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async kakao(
      tokenRequest: TokenRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoTokenResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.kakao(tokenRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath = operationServerMap['AuthApi.kakao']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Access Token을 갱신하는 API입니다.
     * @summary Access Token 갱신
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async reissueRefreshToken(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoTokenResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.reissueRefreshToken(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AuthApi.reissueRefreshToken']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = AuthApiFp(configuration)
  return {
    /**
     * 애플 앱 소셜 로그인을 위한 API입니다.
     * @summary 애플 앱 소셜 로그인
     * @param {AuthApiAppleRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    apple(
      requestParameters: AuthApiAppleRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoTokenResponse> {
      return localVarFp.apple(requestParameters.appleLoginRequest, options).then((request) => request(axios, basePath))
    },
    /**
     * 카카오 앱 소셜 로그인을 위한 API입니다.
     * @summary 카카오 앱 소셜 로그인
     * @param {AuthApiKakaoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    kakao(
      requestParameters: AuthApiKakaoRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoTokenResponse> {
      return localVarFp.kakao(requestParameters.tokenRequest, options).then((request) => request(axios, basePath))
    },
    /**
     * Access Token을 갱신하는 API입니다.
     * @summary Access Token 갱신
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    reissueRefreshToken(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoTokenResponse> {
      return localVarFp.reissueRefreshToken(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for apple operation in AuthApi.
 * @export
 * @interface AuthApiAppleRequest
 */
export interface AuthApiAppleRequest {
  /**
   *
   * @type {AppleLoginRequest}
   * @memberof AuthApiApple
   */
  readonly appleLoginRequest: AppleLoginRequest
}

/**
 * Request parameters for kakao operation in AuthApi.
 * @export
 * @interface AuthApiKakaoRequest
 */
export interface AuthApiKakaoRequest {
  /**
   *
   * @type {TokenRequest}
   * @memberof AuthApiKakao
   */
  readonly tokenRequest: TokenRequest
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
  /**
   * 애플 앱 소셜 로그인을 위한 API입니다.
   * @summary 애플 앱 소셜 로그인
   * @param {AuthApiAppleRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public apple(requestParameters: AuthApiAppleRequest, options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .apple(requestParameters.appleLoginRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 카카오 앱 소셜 로그인을 위한 API입니다.
   * @summary 카카오 앱 소셜 로그인
   * @param {AuthApiKakaoRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public kakao(requestParameters: AuthApiKakaoRequest, options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .kakao(requestParameters.tokenRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Access Token을 갱신하는 API입니다.
   * @summary Access Token 갱신
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public reissueRefreshToken(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .reissueRefreshToken(options)
      .then((request) => request(this.axios, this.basePath))
  }
}
