/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { OnboardingRequest } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
/**
 * OnboardingApi - axios parameter creator
 * @export
 */
export const OnboardingApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 온보딩을 완료하는 API입니다.
     * @summary 온보딩 완료
     * @param {OnboardingRequest} onboardingRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    completeOnboarding: async (
      onboardingRequest: OnboardingRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'onboardingRequest' is not null or undefined
      assertParamExists('completeOnboarding', 'onboardingRequest', onboardingRequest)
      const localVarPath = `/onboarding/complete`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(onboardingRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * OnboardingApi - functional programming interface
 * @export
 */
export const OnboardingApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = OnboardingApiAxiosParamCreator(configuration)
  return {
    /**
     * 온보딩을 완료하는 API입니다.
     * @summary 온보딩 완료
     * @param {OnboardingRequest} onboardingRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async completeOnboarding(
      onboardingRequest: OnboardingRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.completeOnboarding(onboardingRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OnboardingApi.completeOnboarding']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * OnboardingApi - factory interface
 * @export
 */
export const OnboardingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = OnboardingApiFp(configuration)
  return {
    /**
     * 온보딩을 완료하는 API입니다.
     * @summary 온보딩 완료
     * @param {OnboardingApiCompleteOnboardingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    completeOnboarding(
      requestParameters: OnboardingApiCompleteOnboardingRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .completeOnboarding(requestParameters.onboardingRequest, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for completeOnboarding operation in OnboardingApi.
 * @export
 * @interface OnboardingApiCompleteOnboardingRequest
 */
export interface OnboardingApiCompleteOnboardingRequest {
  /**
   *
   * @type {OnboardingRequest}
   * @memberof OnboardingApiCompleteOnboarding
   */
  readonly onboardingRequest: OnboardingRequest
}

/**
 * OnboardingApi - object-oriented interface
 * @export
 * @class OnboardingApi
 * @extends {BaseAPI}
 */
export class OnboardingApi extends BaseAPI {
  /**
   * 온보딩을 완료하는 API입니다.
   * @summary 온보딩 완료
   * @param {OnboardingApiCompleteOnboardingRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OnboardingApi
   */
  public completeOnboarding(
    requestParameters: OnboardingApiCompleteOnboardingRequest,
    options?: RawAxiosRequestConfig
  ) {
    return OnboardingApiFp(this.configuration)
      .completeOnboarding(requestParameters.onboardingRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
