/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { OrderRequestDto } from '../models'
// @ts-ignore
import type { ResponseDtoOrderResponseDto } from '../models'
// @ts-ignore
import type { ResponseDtoPaymentWidgetInfoResponseDto } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
/**
 * OrderApi - axios parameter creator
 * @export
 */
export const OrderApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 결제가 완료된 특정 주문 건의 상세 내역을 조회합니다.
     * @summary 결제 완료 건 상세 조회
     * @param {string} orderId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPaidOrderDetail: async (orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('getPaidOrderDetail', 'orderId', orderId)
      const localVarPath = `/order/{orderId}`.replace(`{${'orderId'}}`, encodeURIComponent(String(orderId)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 프론트에서 결제 성공 후 호출되어 최종 결제 승인을 진행합니다.
     * @summary 결제 성공 후처리
     * @param {string} paymentKey
     * @param {string} orderId
     * @param {number} amount
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handlePaymentSuccess: async (
      paymentKey: string,
      orderId: string,
      amount: number,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'paymentKey' is not null or undefined
      assertParamExists('handlePaymentSuccess', 'paymentKey', paymentKey)
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('handlePaymentSuccess', 'orderId', orderId)
      // verify required parameter 'amount' is not null or undefined
      assertParamExists('handlePaymentSuccess', 'amount', amount)
      const localVarPath = `/order/success`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (paymentKey !== undefined) {
        localVarQueryParameter['paymentKey'] = paymentKey
      }

      if (orderId !== undefined) {
        localVarQueryParameter['orderId'] = orderId
      }

      if (amount !== undefined) {
        localVarQueryParameter['amount'] = amount
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 장바구니에 담긴 상품들을 주문합니다.
     * @summary 상품 주문하기
     * @param {number} storeId
     * @param {OrderRequestDto} orderRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    orderProducts: async (
      storeId: number,
      orderRequestDto: OrderRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'storeId' is not null or undefined
      assertParamExists('orderProducts', 'storeId', storeId)
      // verify required parameter 'orderRequestDto' is not null or undefined
      assertParamExists('orderProducts', 'orderRequestDto', orderRequestDto)
      const localVarPath = `/order/{storeId}`.replace(`{${'storeId'}}`, encodeURIComponent(String(storeId)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(orderRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * OrderApi - functional programming interface
 * @export
 */
export const OrderApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = OrderApiAxiosParamCreator(configuration)
  return {
    /**
     * 결제가 완료된 특정 주문 건의 상세 내역을 조회합니다.
     * @summary 결제 완료 건 상세 조회
     * @param {string} orderId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getPaidOrderDetail(
      orderId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoOrderResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getPaidOrderDetail(orderId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OrderApi.getPaidOrderDetail']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 프론트에서 결제 성공 후 호출되어 최종 결제 승인을 진행합니다.
     * @summary 결제 성공 후처리
     * @param {string} paymentKey
     * @param {string} orderId
     * @param {number} amount
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async handlePaymentSuccess(
      paymentKey: string,
      orderId: string,
      amount: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.handlePaymentSuccess(
        paymentKey,
        orderId,
        amount,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OrderApi.handlePaymentSuccess']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 장바구니에 담긴 상품들을 주문합니다.
     * @summary 상품 주문하기
     * @param {number} storeId
     * @param {OrderRequestDto} orderRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async orderProducts(
      storeId: number,
      orderRequestDto: OrderRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoPaymentWidgetInfoResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.orderProducts(storeId, orderRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['OrderApi.orderProducts']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * OrderApi - factory interface
 * @export
 */
export const OrderApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = OrderApiFp(configuration)
  return {
    /**
     * 결제가 완료된 특정 주문 건의 상세 내역을 조회합니다.
     * @summary 결제 완료 건 상세 조회
     * @param {OrderApiGetPaidOrderDetailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getPaidOrderDetail(
      requestParameters: OrderApiGetPaidOrderDetailRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoOrderResponseDto> {
      return localVarFp
        .getPaidOrderDetail(requestParameters.orderId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 프론트에서 결제 성공 후 호출되어 최종 결제 승인을 진행합니다.
     * @summary 결제 성공 후처리
     * @param {OrderApiHandlePaymentSuccessRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handlePaymentSuccess(
      requestParameters: OrderApiHandlePaymentSuccessRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .handlePaymentSuccess(
          requestParameters.paymentKey,
          requestParameters.orderId,
          requestParameters.amount,
          options
        )
        .then((request) => request(axios, basePath))
    },
    /**
     * 장바구니에 담긴 상품들을 주문합니다.
     * @summary 상품 주문하기
     * @param {OrderApiOrderProductsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    orderProducts(
      requestParameters: OrderApiOrderProductsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoPaymentWidgetInfoResponseDto> {
      return localVarFp
        .orderProducts(requestParameters.storeId, requestParameters.orderRequestDto, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for getPaidOrderDetail operation in OrderApi.
 * @export
 * @interface OrderApiGetPaidOrderDetailRequest
 */
export interface OrderApiGetPaidOrderDetailRequest {
  /**
   *
   * @type {string}
   * @memberof OrderApiGetPaidOrderDetail
   */
  readonly orderId: string
}

/**
 * Request parameters for handlePaymentSuccess operation in OrderApi.
 * @export
 * @interface OrderApiHandlePaymentSuccessRequest
 */
export interface OrderApiHandlePaymentSuccessRequest {
  /**
   *
   * @type {string}
   * @memberof OrderApiHandlePaymentSuccess
   */
  readonly paymentKey: string

  /**
   *
   * @type {string}
   * @memberof OrderApiHandlePaymentSuccess
   */
  readonly orderId: string

  /**
   *
   * @type {number}
   * @memberof OrderApiHandlePaymentSuccess
   */
  readonly amount: number
}

/**
 * Request parameters for orderProducts operation in OrderApi.
 * @export
 * @interface OrderApiOrderProductsRequest
 */
export interface OrderApiOrderProductsRequest {
  /**
   *
   * @type {number}
   * @memberof OrderApiOrderProducts
   */
  readonly storeId: number

  /**
   *
   * @type {OrderRequestDto}
   * @memberof OrderApiOrderProducts
   */
  readonly orderRequestDto: OrderRequestDto
}

/**
 * OrderApi - object-oriented interface
 * @export
 * @class OrderApi
 * @extends {BaseAPI}
 */
export class OrderApi extends BaseAPI {
  /**
   * 결제가 완료된 특정 주문 건의 상세 내역을 조회합니다.
   * @summary 결제 완료 건 상세 조회
   * @param {OrderApiGetPaidOrderDetailRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OrderApi
   */
  public getPaidOrderDetail(requestParameters: OrderApiGetPaidOrderDetailRequest, options?: RawAxiosRequestConfig) {
    return OrderApiFp(this.configuration)
      .getPaidOrderDetail(requestParameters.orderId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 프론트에서 결제 성공 후 호출되어 최종 결제 승인을 진행합니다.
   * @summary 결제 성공 후처리
   * @param {OrderApiHandlePaymentSuccessRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OrderApi
   */
  public handlePaymentSuccess(requestParameters: OrderApiHandlePaymentSuccessRequest, options?: RawAxiosRequestConfig) {
    return OrderApiFp(this.configuration)
      .handlePaymentSuccess(requestParameters.paymentKey, requestParameters.orderId, requestParameters.amount, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 장바구니에 담긴 상품들을 주문합니다.
   * @summary 상품 주문하기
   * @param {OrderApiOrderProductsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof OrderApi
   */
  public orderProducts(requestParameters: OrderApiOrderProductsRequest, options?: RawAxiosRequestConfig) {
    return OrderApiFp(this.configuration)
      .orderProducts(requestParameters.storeId, requestParameters.orderRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
