/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { ParkingLotSearchRequest } from '../models'
// @ts-ignore
import type { ResponseDtoListParkingSimpleResponse } from '../models'
// @ts-ignore
import type { ResponseDtoPageResponseParkingLotListResponse } from '../models'
// @ts-ignore
import type { ResponseDtoPageSearchResponseParkingLotListResponse } from '../models'
// @ts-ignore
import type { ResponseDtoParkingLotDetailResponse } from '../models'
// @ts-ignore
import type { ResponseDtoParkingStatusResponseDto } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
/**
 * ParkingApi - axios parameter creator
 * @export
 */
export const ParkingApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 주차장 상세 정보를 조회하는 API입니다.
     * @summary 주차장 상세 정보 조회
     * @param {string} parkingCode
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingLotDetail: async (parkingCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'parkingCode' is not null or undefined
      assertParamExists('getParkingLotDetail', 'parkingCode', parkingCode)
      const localVarPath = `/parking/detail/{parkingCode}`.replace(
        `{${'parkingCode'}}`,
        encodeURIComponent(String(parkingCode))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 오늘 주차한 내역 중 출차되지 않은 가장 최근 건을 조회합니다.
     * @summary 현재 주차 현황 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/parking/status`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 주문 내역을 출차 처리합니다.
     * @summary 출차 처리하기
     * @param {string} orderId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processDeparture: async (orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('processDeparture', 'orderId', orderId)
      const localVarPath = `/parking/{orderId}/departure`.replace(`{${'orderId'}}`, encodeURIComponent(String(orderId)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 검색어로 주차장을 검색하는 API입니다.
     * @summary 텍스트 기반 주차장 검색
     * @param {ParkingLotSearchRequest} parkingLotSearchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchByText1: async (
      parkingLotSearchRequest: ParkingLotSearchRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'parkingLotSearchRequest' is not null or undefined
      assertParamExists('searchByText1', 'parkingLotSearchRequest', parkingLotSearchRequest)
      const localVarPath = `/parking/text-search`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        parkingLotSearchRequest,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 필터 없이 주차장 이름으로만 전체 주차장을 검색하는 API입니다.
     * @summary 가게 주차장 등록을 위한 이름 검색
     * @param {string} query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchForRegistration1: async (query: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'query' is not null or undefined
      assertParamExists('searchForRegistration1', 'query', query)
      const localVarPath = `/parking/text-search/name`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (query !== undefined) {
        localVarQueryParameter['query'] = query
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 지도에서 주차장을 검색하는 API입니다.
     * @summary 지도 기반 주차장 검색
     * @param {ParkingLotSearchRequest} parkingLotSearchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchParkingLots: async (
      parkingLotSearchRequest: ParkingLotSearchRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'parkingLotSearchRequest' is not null or undefined
      assertParamExists('searchParkingLots', 'parkingLotSearchRequest', parkingLotSearchRequest)
      const localVarPath = `/parking/map-search`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        parkingLotSearchRequest,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 주문 내역의 방문 시간을 현재 시간으로 업데이트합니다.
     * @summary 입차 시간 업데이트
     * @param {string} orderId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateVisitTimeToNow: async (orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'orderId' is not null or undefined
      assertParamExists('updateVisitTimeToNow', 'orderId', orderId)
      const localVarPath = `/parking/{orderId}/arrival`.replace(`{${'orderId'}}`, encodeURIComponent(String(orderId)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * ParkingApi - functional programming interface
 * @export
 */
export const ParkingApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ParkingApiAxiosParamCreator(configuration)
  return {
    /**
     * 주차장 상세 정보를 조회하는 API입니다.
     * @summary 주차장 상세 정보 조회
     * @param {string} parkingCode
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getParkingLotDetail(
      parkingCode: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoParkingLotDetailResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getParkingLotDetail(parkingCode, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ParkingApi.getParkingLotDetail']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 오늘 주차한 내역 중 출차되지 않은 가장 최근 건을 조회합니다.
     * @summary 현재 주차 현황 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getParkingStatus(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoParkingStatusResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getParkingStatus(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ParkingApi.getParkingStatus']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 주문 내역을 출차 처리합니다.
     * @summary 출차 처리하기
     * @param {string} orderId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async processDeparture(
      orderId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.processDeparture(orderId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ParkingApi.processDeparture']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 검색어로 주차장을 검색하는 API입니다.
     * @summary 텍스트 기반 주차장 검색
     * @param {ParkingLotSearchRequest} parkingLotSearchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchByText1(
      parkingLotSearchRequest: ParkingLotSearchRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoPageSearchResponseParkingLotListResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.searchByText1(parkingLotSearchRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ParkingApi.searchByText1']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 필터 없이 주차장 이름으로만 전체 주차장을 검색하는 API입니다.
     * @summary 가게 주차장 등록을 위한 이름 검색
     * @param {string} query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchForRegistration1(
      query: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListParkingSimpleResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.searchForRegistration1(query, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ParkingApi.searchForRegistration1']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 지도에서 주차장을 검색하는 API입니다.
     * @summary 지도 기반 주차장 검색
     * @param {ParkingLotSearchRequest} parkingLotSearchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchParkingLots(
      parkingLotSearchRequest: ParkingLotSearchRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoPageResponseParkingLotListResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.searchParkingLots(parkingLotSearchRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ParkingApi.searchParkingLots']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 주문 내역의 방문 시간을 현재 시간으로 업데이트합니다.
     * @summary 입차 시간 업데이트
     * @param {string} orderId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateVisitTimeToNow(
      orderId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoParkingStatusResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateVisitTimeToNow(orderId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ParkingApi.updateVisitTimeToNow']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * ParkingApi - factory interface
 * @export
 */
export const ParkingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = ParkingApiFp(configuration)
  return {
    /**
     * 주차장 상세 정보를 조회하는 API입니다.
     * @summary 주차장 상세 정보 조회
     * @param {ParkingApiGetParkingLotDetailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingLotDetail(
      requestParameters: ParkingApiGetParkingLotDetailRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoParkingLotDetailResponse> {
      return localVarFp
        .getParkingLotDetail(requestParameters.parkingCode, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 오늘 주차한 내역 중 출차되지 않은 가장 최근 건을 조회합니다.
     * @summary 현재 주차 현황 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingStatus(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoParkingStatusResponseDto> {
      return localVarFp.getParkingStatus(options).then((request) => request(axios, basePath))
    },
    /**
     * 주문 내역을 출차 처리합니다.
     * @summary 출차 처리하기
     * @param {ParkingApiProcessDepartureRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processDeparture(
      requestParameters: ParkingApiProcessDepartureRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp.processDeparture(requestParameters.orderId, options).then((request) => request(axios, basePath))
    },
    /**
     * 검색어로 주차장을 검색하는 API입니다.
     * @summary 텍스트 기반 주차장 검색
     * @param {ParkingApiSearchByText1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchByText1(
      requestParameters: ParkingApiSearchByText1Request,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoPageSearchResponseParkingLotListResponse> {
      return localVarFp
        .searchByText1(requestParameters.parkingLotSearchRequest, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 필터 없이 주차장 이름으로만 전체 주차장을 검색하는 API입니다.
     * @summary 가게 주차장 등록을 위한 이름 검색
     * @param {ParkingApiSearchForRegistration1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchForRegistration1(
      requestParameters: ParkingApiSearchForRegistration1Request,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoListParkingSimpleResponse> {
      return localVarFp
        .searchForRegistration1(requestParameters.query, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 지도에서 주차장을 검색하는 API입니다.
     * @summary 지도 기반 주차장 검색
     * @param {ParkingApiSearchParkingLotsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchParkingLots(
      requestParameters: ParkingApiSearchParkingLotsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoPageResponseParkingLotListResponse> {
      return localVarFp
        .searchParkingLots(requestParameters.parkingLotSearchRequest, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 주문 내역의 방문 시간을 현재 시간으로 업데이트합니다.
     * @summary 입차 시간 업데이트
     * @param {ParkingApiUpdateVisitTimeToNowRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateVisitTimeToNow(
      requestParameters: ParkingApiUpdateVisitTimeToNowRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoParkingStatusResponseDto> {
      return localVarFp
        .updateVisitTimeToNow(requestParameters.orderId, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for getParkingLotDetail operation in ParkingApi.
 * @export
 * @interface ParkingApiGetParkingLotDetailRequest
 */
export interface ParkingApiGetParkingLotDetailRequest {
  /**
   *
   * @type {string}
   * @memberof ParkingApiGetParkingLotDetail
   */
  readonly parkingCode: string
}

/**
 * Request parameters for processDeparture operation in ParkingApi.
 * @export
 * @interface ParkingApiProcessDepartureRequest
 */
export interface ParkingApiProcessDepartureRequest {
  /**
   *
   * @type {string}
   * @memberof ParkingApiProcessDeparture
   */
  readonly orderId: string
}

/**
 * Request parameters for searchByText1 operation in ParkingApi.
 * @export
 * @interface ParkingApiSearchByText1Request
 */
export interface ParkingApiSearchByText1Request {
  /**
   *
   * @type {ParkingLotSearchRequest}
   * @memberof ParkingApiSearchByText1
   */
  readonly parkingLotSearchRequest: ParkingLotSearchRequest
}

/**
 * Request parameters for searchForRegistration1 operation in ParkingApi.
 * @export
 * @interface ParkingApiSearchForRegistration1Request
 */
export interface ParkingApiSearchForRegistration1Request {
  /**
   *
   * @type {string}
   * @memberof ParkingApiSearchForRegistration1
   */
  readonly query: string
}

/**
 * Request parameters for searchParkingLots operation in ParkingApi.
 * @export
 * @interface ParkingApiSearchParkingLotsRequest
 */
export interface ParkingApiSearchParkingLotsRequest {
  /**
   *
   * @type {ParkingLotSearchRequest}
   * @memberof ParkingApiSearchParkingLots
   */
  readonly parkingLotSearchRequest: ParkingLotSearchRequest
}

/**
 * Request parameters for updateVisitTimeToNow operation in ParkingApi.
 * @export
 * @interface ParkingApiUpdateVisitTimeToNowRequest
 */
export interface ParkingApiUpdateVisitTimeToNowRequest {
  /**
   *
   * @type {string}
   * @memberof ParkingApiUpdateVisitTimeToNow
   */
  readonly orderId: string
}

/**
 * ParkingApi - object-oriented interface
 * @export
 * @class ParkingApi
 * @extends {BaseAPI}
 */
export class ParkingApi extends BaseAPI {
  /**
   * 주차장 상세 정보를 조회하는 API입니다.
   * @summary 주차장 상세 정보 조회
   * @param {ParkingApiGetParkingLotDetailRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ParkingApi
   */
  public getParkingLotDetail(requestParameters: ParkingApiGetParkingLotDetailRequest, options?: RawAxiosRequestConfig) {
    return ParkingApiFp(this.configuration)
      .getParkingLotDetail(requestParameters.parkingCode, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 오늘 주차한 내역 중 출차되지 않은 가장 최근 건을 조회합니다.
   * @summary 현재 주차 현황 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ParkingApi
   */
  public getParkingStatus(options?: RawAxiosRequestConfig) {
    return ParkingApiFp(this.configuration)
      .getParkingStatus(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 주문 내역을 출차 처리합니다.
   * @summary 출차 처리하기
   * @param {ParkingApiProcessDepartureRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ParkingApi
   */
  public processDeparture(requestParameters: ParkingApiProcessDepartureRequest, options?: RawAxiosRequestConfig) {
    return ParkingApiFp(this.configuration)
      .processDeparture(requestParameters.orderId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 검색어로 주차장을 검색하는 API입니다.
   * @summary 텍스트 기반 주차장 검색
   * @param {ParkingApiSearchByText1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ParkingApi
   */
  public searchByText1(requestParameters: ParkingApiSearchByText1Request, options?: RawAxiosRequestConfig) {
    return ParkingApiFp(this.configuration)
      .searchByText1(requestParameters.parkingLotSearchRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 필터 없이 주차장 이름으로만 전체 주차장을 검색하는 API입니다.
   * @summary 가게 주차장 등록을 위한 이름 검색
   * @param {ParkingApiSearchForRegistration1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ParkingApi
   */
  public searchForRegistration1(
    requestParameters: ParkingApiSearchForRegistration1Request,
    options?: RawAxiosRequestConfig
  ) {
    return ParkingApiFp(this.configuration)
      .searchForRegistration1(requestParameters.query, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 지도에서 주차장을 검색하는 API입니다.
   * @summary 지도 기반 주차장 검색
   * @param {ParkingApiSearchParkingLotsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ParkingApi
   */
  public searchParkingLots(requestParameters: ParkingApiSearchParkingLotsRequest, options?: RawAxiosRequestConfig) {
    return ParkingApiFp(this.configuration)
      .searchParkingLots(requestParameters.parkingLotSearchRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 주문 내역의 방문 시간을 현재 시간으로 업데이트합니다.
   * @summary 입차 시간 업데이트
   * @param {ParkingApiUpdateVisitTimeToNowRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ParkingApi
   */
  public updateVisitTimeToNow(
    requestParameters: ParkingApiUpdateVisitTimeToNowRequest,
    options?: RawAxiosRequestConfig
  ) {
    return ParkingApiFp(this.configuration)
      .updateVisitTimeToNow(requestParameters.orderId, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
