/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { CategoryResponse } from '../models'
// @ts-ignore
import type { OnboardingRequest } from '../models'
// @ts-ignore
import type { RegisterRequest } from '../models'
// @ts-ignore
import type { ResponseDtoTermsResponse } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
/**
 * RegisterApi - axios parameter creator
 * @export
 */
export const RegisterApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 온보딩을 완료하는 API입니다.
     * @summary 온보딩 완료
     * @param {OnboardingRequest} onboardingRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    completeOnboarding: async (
      onboardingRequest: OnboardingRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'onboardingRequest' is not null or undefined
      assertParamExists('completeOnboarding', 'onboardingRequest', onboardingRequest)
      const localVarPath = `/register/onboarding`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(onboardingRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 온보딩 시 카테고리를 조회하는 API입니다.
     * @summary 온보딩 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/register/onboarding`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 회원가입 시 약관을 조회하는 API입니다.
     * @summary 약관 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTerms: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/register/terms`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 회원가입 시 약관 동의를 위한 API입니다.
     * @summary 회원가입- 약관동의
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerAgreements: async (
      registerRequest: RegisterRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'registerRequest' is not null or undefined
      assertParamExists('registerAgreements', 'registerRequest', registerRequest)
      const localVarPath = `/register/resister`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(registerRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * RegisterApi - functional programming interface
 * @export
 */
export const RegisterApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RegisterApiAxiosParamCreator(configuration)
  return {
    /**
     * 온보딩을 완료하는 API입니다.
     * @summary 온보딩 완료
     * @param {OnboardingRequest} onboardingRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async completeOnboarding(
      onboardingRequest: OnboardingRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.completeOnboarding(onboardingRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['RegisterApi.completeOnboarding']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 온보딩 시 카테고리를 조회하는 API입니다.
     * @summary 온보딩 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCategories(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getCategories(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['RegisterApi.getCategories']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 회원가입 시 약관을 조회하는 API입니다.
     * @summary 약관 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getTerms(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoTermsResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getTerms(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['RegisterApi.getTerms']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 회원가입 시 약관 동의를 위한 API입니다.
     * @summary 회원가입- 약관동의
     * @param {RegisterRequest} registerRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async registerAgreements(
      registerRequest: RegisterRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.registerAgreements(registerRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['RegisterApi.registerAgreements']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * RegisterApi - factory interface
 * @export
 */
export const RegisterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = RegisterApiFp(configuration)
  return {
    /**
     * 온보딩을 완료하는 API입니다.
     * @summary 온보딩 완료
     * @param {RegisterApiCompleteOnboardingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    completeOnboarding(
      requestParameters: RegisterApiCompleteOnboardingRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .completeOnboarding(requestParameters.onboardingRequest, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 온보딩 시 카테고리를 조회하는 API입니다.
     * @summary 온보딩 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCategories(options?: RawAxiosRequestConfig): AxiosPromise<CategoryResponse> {
      return localVarFp.getCategories(options).then((request) => request(axios, basePath))
    },
    /**
     * 회원가입 시 약관을 조회하는 API입니다.
     * @summary 약관 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getTerms(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoTermsResponse> {
      return localVarFp.getTerms(options).then((request) => request(axios, basePath))
    },
    /**
     * 회원가입 시 약관 동의를 위한 API입니다.
     * @summary 회원가입- 약관동의
     * @param {RegisterApiRegisterAgreementsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerAgreements(
      requestParameters: RegisterApiRegisterAgreementsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .registerAgreements(requestParameters.registerRequest, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for completeOnboarding operation in RegisterApi.
 * @export
 * @interface RegisterApiCompleteOnboardingRequest
 */
export interface RegisterApiCompleteOnboardingRequest {
  /**
   *
   * @type {OnboardingRequest}
   * @memberof RegisterApiCompleteOnboarding
   */
  readonly onboardingRequest: OnboardingRequest
}

/**
 * Request parameters for registerAgreements operation in RegisterApi.
 * @export
 * @interface RegisterApiRegisterAgreementsRequest
 */
export interface RegisterApiRegisterAgreementsRequest {
  /**
   *
   * @type {RegisterRequest}
   * @memberof RegisterApiRegisterAgreements
   */
  readonly registerRequest: RegisterRequest
}

/**
 * RegisterApi - object-oriented interface
 * @export
 * @class RegisterApi
 * @extends {BaseAPI}
 */
export class RegisterApi extends BaseAPI {
  /**
   * 온보딩을 완료하는 API입니다.
   * @summary 온보딩 완료
   * @param {RegisterApiCompleteOnboardingRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegisterApi
   */
  public completeOnboarding(requestParameters: RegisterApiCompleteOnboardingRequest, options?: RawAxiosRequestConfig) {
    return RegisterApiFp(this.configuration)
      .completeOnboarding(requestParameters.onboardingRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 온보딩 시 카테고리를 조회하는 API입니다.
   * @summary 온보딩 카테고리 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegisterApi
   */
  public getCategories(options?: RawAxiosRequestConfig) {
    return RegisterApiFp(this.configuration)
      .getCategories(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 회원가입 시 약관을 조회하는 API입니다.
   * @summary 약관 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegisterApi
   */
  public getTerms(options?: RawAxiosRequestConfig) {
    return RegisterApiFp(this.configuration)
      .getTerms(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 회원가입 시 약관 동의를 위한 API입니다.
   * @summary 회원가입- 약관동의
   * @param {RegisterApiRegisterAgreementsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegisterApi
   */
  public registerAgreements(requestParameters: RegisterApiRegisterAgreementsRequest, options?: RawAxiosRequestConfig) {
    return RegisterApiFp(this.configuration)
      .registerAgreements(requestParameters.registerRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
