/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { ResponseDtoSearchSuggestionResponse } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
/**
 * SearchApi - axios parameter creator
 * @export
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 로그인한 사용자의 모든 최근 검색어를 삭제합니다.
     * @summary 최근 검색어 전체 삭제
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteAllRecentSearches: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/search/recent`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 로그인한 사용자의 최근 검색어를 삭제합니다.
     * @summary 최근 검색어 삭제
     * @param {number} searchId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteRecentSearch: async (searchId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'searchId' is not null or undefined
      assertParamExists('deleteRecentSearch', 'searchId', searchId)
      const localVarPath = `/search/recent/{searchId}`.replace(`{${'searchId'}}`, encodeURIComponent(String(searchId)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 로그인한 사용자에 대한 추천 검색어와 최근 검색어를 조회합니다.
     * @summary 검색 제안 조회 (추천 검색어 + 최근 검색어)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSearchSuggestions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/search/suggestions`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * SearchApi - functional programming interface
 * @export
 */
export const SearchApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
  return {
    /**
     * 로그인한 사용자의 모든 최근 검색어를 삭제합니다.
     * @summary 최근 검색어 전체 삭제
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteAllRecentSearches(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAllRecentSearches(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['SearchApi.deleteAllRecentSearches']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 로그인한 사용자의 최근 검색어를 삭제합니다.
     * @summary 최근 검색어 삭제
     * @param {number} searchId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteRecentSearch(
      searchId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteRecentSearch(searchId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['SearchApi.deleteRecentSearch']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 로그인한 사용자에 대한 추천 검색어와 최근 검색어를 조회합니다.
     * @summary 검색 제안 조회 (추천 검색어 + 최근 검색어)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getSearchSuggestions(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoSearchSuggestionResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getSearchSuggestions(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['SearchApi.getSearchSuggestions']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * SearchApi - factory interface
 * @export
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = SearchApiFp(configuration)
  return {
    /**
     * 로그인한 사용자의 모든 최근 검색어를 삭제합니다.
     * @summary 최근 검색어 전체 삭제
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteAllRecentSearches(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoUnit> {
      return localVarFp.deleteAllRecentSearches(options).then((request) => request(axios, basePath))
    },
    /**
     * 로그인한 사용자의 최근 검색어를 삭제합니다.
     * @summary 최근 검색어 삭제
     * @param {SearchApiDeleteRecentSearchRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteRecentSearch(
      requestParameters: SearchApiDeleteRecentSearchRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .deleteRecentSearch(requestParameters.searchId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 로그인한 사용자에 대한 추천 검색어와 최근 검색어를 조회합니다.
     * @summary 검색 제안 조회 (추천 검색어 + 최근 검색어)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSearchSuggestions(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoSearchSuggestionResponse> {
      return localVarFp.getSearchSuggestions(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for deleteRecentSearch operation in SearchApi.
 * @export
 * @interface SearchApiDeleteRecentSearchRequest
 */
export interface SearchApiDeleteRecentSearchRequest {
  /**
   *
   * @type {number}
   * @memberof SearchApiDeleteRecentSearch
   */
  readonly searchId: number
}

/**
 * SearchApi - object-oriented interface
 * @export
 * @class SearchApi
 * @extends {BaseAPI}
 */
export class SearchApi extends BaseAPI {
  /**
   * 로그인한 사용자의 모든 최근 검색어를 삭제합니다.
   * @summary 최근 검색어 전체 삭제
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SearchApi
   */
  public deleteAllRecentSearches(options?: RawAxiosRequestConfig) {
    return SearchApiFp(this.configuration)
      .deleteAllRecentSearches(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 로그인한 사용자의 최근 검색어를 삭제합니다.
   * @summary 최근 검색어 삭제
   * @param {SearchApiDeleteRecentSearchRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SearchApi
   */
  public deleteRecentSearch(requestParameters: SearchApiDeleteRecentSearchRequest, options?: RawAxiosRequestConfig) {
    return SearchApiFp(this.configuration)
      .deleteRecentSearch(requestParameters.searchId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 로그인한 사용자에 대한 추천 검색어와 최근 검색어를 조회합니다.
   * @summary 검색 제안 조회 (추천 검색어 + 최근 검색어)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SearchApi
   */
  public getSearchSuggestions(options?: RawAxiosRequestConfig) {
    return SearchApiFp(this.configuration)
      .getSearchSuggestions(options)
      .then((request) => request(this.axios, this.basePath))
  }
}
