/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { ResponseDtoListSearchItemResponse } from '../models'
/**
 * SearchApi - axios parameter creator
 * @export
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 검색어로 네이버 API를 통해 장소를 검색합니다.
     * @summary 네이버 검색 API를 이용한 텍스트 검색
     * @param {string} query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    search1: async (query: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'query' is not null or undefined
      assertParamExists('search1', 'query', query)
      const localVarPath = `/text-search`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (query !== undefined) {
        localVarQueryParameter['query'] = query
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * SearchApi - functional programming interface
 * @export
 */
export const SearchApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
  return {
    /**
     * 검색어로 네이버 API를 통해 장소를 검색합니다.
     * @summary 네이버 검색 API를 이용한 텍스트 검색
     * @param {string} query
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async search1(
      query: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListSearchItemResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.search1(query, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['SearchApi.search1']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * SearchApi - factory interface
 * @export
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = SearchApiFp(configuration)
  return {
    /**
     * 검색어로 네이버 API를 통해 장소를 검색합니다.
     * @summary 네이버 검색 API를 이용한 텍스트 검색
     * @param {SearchApiSearch1Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    search1(
      requestParameters: SearchApiSearch1Request,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoListSearchItemResponse> {
      return localVarFp.search1(requestParameters.query, options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for search1 operation in SearchApi.
 * @export
 * @interface SearchApiSearch1Request
 */
export interface SearchApiSearch1Request {
  /**
   *
   * @type {string}
   * @memberof SearchApiSearch1
   */
  readonly query: string
}

/**
 * SearchApi - object-oriented interface
 * @export
 * @class SearchApi
 * @extends {BaseAPI}
 */
export class SearchApi extends BaseAPI {
  /**
   * 검색어로 네이버 API를 통해 장소를 검색합니다.
   * @summary 네이버 검색 API를 이용한 텍스트 검색
   * @param {SearchApiSearch1Request} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SearchApi
   */
  public search1(requestParameters: SearchApiSearch1Request, options?: RawAxiosRequestConfig) {
    return SearchApiFp(this.configuration)
      .search1(requestParameters.query, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
