/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { BenefitRequestDto } from '../models'
// @ts-ignore
import type { ProductRequestDto } from '../models'
// @ts-ignore
import type { ResponseDtoListMyStoreInfo } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
/**
 * StorekeeperApi - axios parameter creator
 * @export
 */
export const StorekeeperApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 특정 가게에 구매 금액별 주차 할인 혜택을 추가합니다.
     * @summary 가게 주차 할인 혜택 추가
     * @param {number} storeId
     * @param {BenefitRequestDto} benefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addParkingBenefit: async (
      storeId: number,
      benefitRequestDto: BenefitRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'storeId' is not null or undefined
      assertParamExists('addParkingBenefit', 'storeId', storeId)
      // verify required parameter 'benefitRequestDto' is not null or undefined
      assertParamExists('addParkingBenefit', 'benefitRequestDto', benefitRequestDto)
      const localVarPath = `/storekeeper/{storeId}/benefits`.replace(
        `{${'storeId'}}`,
        encodeURIComponent(String(storeId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(benefitRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 특정 가게에 새로운 상품을 추가합니다.
     * @summary 가게 상품 추가
     * @param {number} storeId
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProduct: async (
      storeId: number,
      productRequestDto: ProductRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'storeId' is not null or undefined
      assertParamExists('addProduct', 'storeId', storeId)
      // verify required parameter 'productRequestDto' is not null or undefined
      assertParamExists('addProduct', 'productRequestDto', productRequestDto)
      const localVarPath = `/storekeeper/{storeId}/products`.replace(
        `{${'storeId'}}`,
        encodeURIComponent(String(storeId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(productRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 가게의 주차 할인 혜택을 삭제합니다.
     * @summary 가게 주차 할인 혜택 삭제
     * @param {number} benefitId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteParkingBenefit: async (benefitId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'benefitId' is not null or undefined
      assertParamExists('deleteParkingBenefit', 'benefitId', benefitId)
      const localVarPath = `/storekeeper/benefits/{benefitId}`.replace(
        `{${'benefitId'}}`,
        encodeURIComponent(String(benefitId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 특정 상품을 삭제합니다.
     * @summary 가게 상품 삭제
     * @param {number} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProduct: async (productId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'productId' is not null or undefined
      assertParamExists('deleteProduct', 'productId', productId)
      const localVarPath = `/storekeeper/products/{productId}`.replace(
        `{${'productId'}}`,
        encodeURIComponent(String(productId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 로그인한 가게 주인이 소유한 가게들의 목록을 조회합니다.
     * @summary 내 가게 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMyStores: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/storekeeper/my-stores`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 로그인한 사용자가 특정 가게의 소유권을 신청합니다.
     * @summary 가게 소유권 신청
     * @param {number} storeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    requestOwnership: async (storeId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'storeId' is not null or undefined
      assertParamExists('requestOwnership', 'storeId', storeId)
      const localVarPath = `/storekeeper/request-ownership/{storeId}`.replace(
        `{${'storeId'}}`,
        encodeURIComponent(String(storeId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 가게의 주차 할인 혜택을 수정합니다.
     * @summary 가게 주차 할인 혜택 수정
     * @param {number} benefitId
     * @param {BenefitRequestDto} benefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateParkingBenefit: async (
      benefitId: number,
      benefitRequestDto: BenefitRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'benefitId' is not null or undefined
      assertParamExists('updateParkingBenefit', 'benefitId', benefitId)
      // verify required parameter 'benefitRequestDto' is not null or undefined
      assertParamExists('updateParkingBenefit', 'benefitRequestDto', benefitRequestDto)
      const localVarPath = `/storekeeper/benefits/{benefitId}`.replace(
        `{${'benefitId'}}`,
        encodeURIComponent(String(benefitId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(benefitRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 특정 상품의 정보를 수정합니다.
     * @summary 가게 상품 수정
     * @param {number} productId
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProduct: async (
      productId: number,
      productRequestDto: ProductRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'productId' is not null or undefined
      assertParamExists('updateProduct', 'productId', productId)
      // verify required parameter 'productRequestDto' is not null or undefined
      assertParamExists('updateProduct', 'productRequestDto', productRequestDto)
      const localVarPath = `/storekeeper/products/{productId}`.replace(
        `{${'productId'}}`,
        encodeURIComponent(String(productId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(productRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * StorekeeperApi - functional programming interface
 * @export
 */
export const StorekeeperApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = StorekeeperApiAxiosParamCreator(configuration)
  return {
    /**
     * 특정 가게에 구매 금액별 주차 할인 혜택을 추가합니다.
     * @summary 가게 주차 할인 혜택 추가
     * @param {number} storeId
     * @param {BenefitRequestDto} benefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addParkingBenefit(
      storeId: number,
      benefitRequestDto: BenefitRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addParkingBenefit(storeId, benefitRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.addParkingBenefit']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 특정 가게에 새로운 상품을 추가합니다.
     * @summary 가게 상품 추가
     * @param {number} storeId
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addProduct(
      storeId: number,
      productRequestDto: ProductRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addProduct(storeId, productRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.addProduct']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 가게의 주차 할인 혜택을 삭제합니다.
     * @summary 가게 주차 할인 혜택 삭제
     * @param {number} benefitId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteParkingBenefit(
      benefitId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteParkingBenefit(benefitId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.deleteParkingBenefit']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 특정 상품을 삭제합니다.
     * @summary 가게 상품 삭제
     * @param {number} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteProduct(
      productId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProduct(productId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.deleteProduct']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 로그인한 가게 주인이 소유한 가게들의 목록을 조회합니다.
     * @summary 내 가게 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getMyStores(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListMyStoreInfo>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getMyStores(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.getMyStores']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 로그인한 사용자가 특정 가게의 소유권을 신청합니다.
     * @summary 가게 소유권 신청
     * @param {number} storeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async requestOwnership(
      storeId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.requestOwnership(storeId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.requestOwnership']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 가게의 주차 할인 혜택을 수정합니다.
     * @summary 가게 주차 할인 혜택 수정
     * @param {number} benefitId
     * @param {BenefitRequestDto} benefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateParkingBenefit(
      benefitId: number,
      benefitRequestDto: BenefitRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateParkingBenefit(
        benefitId,
        benefitRequestDto,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.updateParkingBenefit']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 특정 상품의 정보를 수정합니다.
     * @summary 가게 상품 수정
     * @param {number} productId
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateProduct(
      productId: number,
      productRequestDto: ProductRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateProduct(productId, productRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.updateProduct']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * StorekeeperApi - factory interface
 * @export
 */
export const StorekeeperApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = StorekeeperApiFp(configuration)
  return {
    /**
     * 특정 가게에 구매 금액별 주차 할인 혜택을 추가합니다.
     * @summary 가게 주차 할인 혜택 추가
     * @param {StorekeeperApiAddParkingBenefitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addParkingBenefit(
      requestParameters: StorekeeperApiAddParkingBenefitRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .addParkingBenefit(requestParameters.storeId, requestParameters.benefitRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 특정 가게에 새로운 상품을 추가합니다.
     * @summary 가게 상품 추가
     * @param {StorekeeperApiAddProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProduct(
      requestParameters: StorekeeperApiAddProductRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .addProduct(requestParameters.storeId, requestParameters.productRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 가게의 주차 할인 혜택을 삭제합니다.
     * @summary 가게 주차 할인 혜택 삭제
     * @param {StorekeeperApiDeleteParkingBenefitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteParkingBenefit(
      requestParameters: StorekeeperApiDeleteParkingBenefitRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .deleteParkingBenefit(requestParameters.benefitId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 특정 상품을 삭제합니다.
     * @summary 가게 상품 삭제
     * @param {StorekeeperApiDeleteProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProduct(
      requestParameters: StorekeeperApiDeleteProductRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp.deleteProduct(requestParameters.productId, options).then((request) => request(axios, basePath))
    },
    /**
     * 로그인한 가게 주인이 소유한 가게들의 목록을 조회합니다.
     * @summary 내 가게 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMyStores(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoListMyStoreInfo> {
      return localVarFp.getMyStores(options).then((request) => request(axios, basePath))
    },
    /**
     * 로그인한 사용자가 특정 가게의 소유권을 신청합니다.
     * @summary 가게 소유권 신청
     * @param {StorekeeperApiRequestOwnershipRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    requestOwnership(
      requestParameters: StorekeeperApiRequestOwnershipRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp.requestOwnership(requestParameters.storeId, options).then((request) => request(axios, basePath))
    },
    /**
     * 가게의 주차 할인 혜택을 수정합니다.
     * @summary 가게 주차 할인 혜택 수정
     * @param {StorekeeperApiUpdateParkingBenefitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateParkingBenefit(
      requestParameters: StorekeeperApiUpdateParkingBenefitRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .updateParkingBenefit(requestParameters.benefitId, requestParameters.benefitRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 특정 상품의 정보를 수정합니다.
     * @summary 가게 상품 수정
     * @param {StorekeeperApiUpdateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProduct(
      requestParameters: StorekeeperApiUpdateProductRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .updateProduct(requestParameters.productId, requestParameters.productRequestDto, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for addParkingBenefit operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiAddParkingBenefitRequest
 */
export interface StorekeeperApiAddParkingBenefitRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiAddParkingBenefit
   */
  readonly storeId: number

  /**
   *
   * @type {BenefitRequestDto}
   * @memberof StorekeeperApiAddParkingBenefit
   */
  readonly benefitRequestDto: BenefitRequestDto
}

/**
 * Request parameters for addProduct operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiAddProductRequest
 */
export interface StorekeeperApiAddProductRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiAddProduct
   */
  readonly storeId: number

  /**
   *
   * @type {ProductRequestDto}
   * @memberof StorekeeperApiAddProduct
   */
  readonly productRequestDto: ProductRequestDto
}

/**
 * Request parameters for deleteParkingBenefit operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiDeleteParkingBenefitRequest
 */
export interface StorekeeperApiDeleteParkingBenefitRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiDeleteParkingBenefit
   */
  readonly benefitId: number
}

/**
 * Request parameters for deleteProduct operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiDeleteProductRequest
 */
export interface StorekeeperApiDeleteProductRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiDeleteProduct
   */
  readonly productId: number
}

/**
 * Request parameters for requestOwnership operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiRequestOwnershipRequest
 */
export interface StorekeeperApiRequestOwnershipRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiRequestOwnership
   */
  readonly storeId: number
}

/**
 * Request parameters for updateParkingBenefit operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiUpdateParkingBenefitRequest
 */
export interface StorekeeperApiUpdateParkingBenefitRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiUpdateParkingBenefit
   */
  readonly benefitId: number

  /**
   *
   * @type {BenefitRequestDto}
   * @memberof StorekeeperApiUpdateParkingBenefit
   */
  readonly benefitRequestDto: BenefitRequestDto
}

/**
 * Request parameters for updateProduct operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiUpdateProductRequest
 */
export interface StorekeeperApiUpdateProductRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiUpdateProduct
   */
  readonly productId: number

  /**
   *
   * @type {ProductRequestDto}
   * @memberof StorekeeperApiUpdateProduct
   */
  readonly productRequestDto: ProductRequestDto
}

/**
 * StorekeeperApi - object-oriented interface
 * @export
 * @class StorekeeperApi
 * @extends {BaseAPI}
 */
export class StorekeeperApi extends BaseAPI {
  /**
   * 특정 가게에 구매 금액별 주차 할인 혜택을 추가합니다.
   * @summary 가게 주차 할인 혜택 추가
   * @param {StorekeeperApiAddParkingBenefitRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public addParkingBenefit(requestParameters: StorekeeperApiAddParkingBenefitRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .addParkingBenefit(requestParameters.storeId, requestParameters.benefitRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 특정 가게에 새로운 상품을 추가합니다.
   * @summary 가게 상품 추가
   * @param {StorekeeperApiAddProductRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public addProduct(requestParameters: StorekeeperApiAddProductRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .addProduct(requestParameters.storeId, requestParameters.productRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 가게의 주차 할인 혜택을 삭제합니다.
   * @summary 가게 주차 할인 혜택 삭제
   * @param {StorekeeperApiDeleteParkingBenefitRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public deleteParkingBenefit(
    requestParameters: StorekeeperApiDeleteParkingBenefitRequest,
    options?: RawAxiosRequestConfig
  ) {
    return StorekeeperApiFp(this.configuration)
      .deleteParkingBenefit(requestParameters.benefitId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 특정 상품을 삭제합니다.
   * @summary 가게 상품 삭제
   * @param {StorekeeperApiDeleteProductRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public deleteProduct(requestParameters: StorekeeperApiDeleteProductRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .deleteProduct(requestParameters.productId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 로그인한 가게 주인이 소유한 가게들의 목록을 조회합니다.
   * @summary 내 가게 목록 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public getMyStores(options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .getMyStores(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 로그인한 사용자가 특정 가게의 소유권을 신청합니다.
   * @summary 가게 소유권 신청
   * @param {StorekeeperApiRequestOwnershipRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public requestOwnership(requestParameters: StorekeeperApiRequestOwnershipRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .requestOwnership(requestParameters.storeId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 가게의 주차 할인 혜택을 수정합니다.
   * @summary 가게 주차 할인 혜택 수정
   * @param {StorekeeperApiUpdateParkingBenefitRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public updateParkingBenefit(
    requestParameters: StorekeeperApiUpdateParkingBenefitRequest,
    options?: RawAxiosRequestConfig
  ) {
    return StorekeeperApiFp(this.configuration)
      .updateParkingBenefit(requestParameters.benefitId, requestParameters.benefitRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 특정 상품의 정보를 수정합니다.
   * @summary 가게 상품 수정
   * @param {StorekeeperApiUpdateProductRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public updateProduct(requestParameters: StorekeeperApiUpdateProductRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .updateProduct(requestParameters.productId, requestParameters.productRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
