/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { AdminLoginRequest } from '../models'
// @ts-ignore
import type { LinkParkingRequestDto } from '../models'
// @ts-ignore
import type { MyStoreUpdateRequest } from '../models'
// @ts-ignore
import type { ParkingBenefitRequestDto } from '../models'
// @ts-ignore
import type { ParkingLotManualRequestDto } from '../models'
// @ts-ignore
import type { ProductRequestDto } from '../models'
// @ts-ignore
import type { ResponseDtoBoolean } from '../models'
// @ts-ignore
import type { ResponseDtoListAssociatedParkingLotResponseDto } from '../models'
// @ts-ignore
import type { ResponseDtoListParkingBenefitDto } from '../models'
// @ts-ignore
import type { ResponseDtoListProductResponseDto } from '../models'
// @ts-ignore
import type { ResponseDtoMyStoreResponse } from '../models'
// @ts-ignore
import type { ResponseDtoParkingBenefitDto } from '../models'
// @ts-ignore
import type { ResponseDtoProductResponseDto } from '../models'
// @ts-ignore
import type { ResponseDtoTokenResponse } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
// @ts-ignore
import type { StorekeeperRegisterRequest } from '../models'
/**
 * StorekeeperApi - axios parameter creator
 * @export
 */
export const StorekeeperApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 내 가게에 새로운 주차 혜택(구매 금액별 할인)을 추가합니다.
     * @summary 주차 혜택 추가
     * @param {ParkingBenefitRequestDto} parkingBenefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addParkingBenefit: async (
      parkingBenefitRequestDto: ParkingBenefitRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'parkingBenefitRequestDto' is not null or undefined
      assertParamExists('addParkingBenefit', 'parkingBenefitRequestDto', parkingBenefitRequestDto)
      const localVarPath = `/storekeeper/benefits`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        parkingBenefitRequestDto,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게에 새로운 상품을 등록합니다.
     * @summary 가게 상품 추가
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProduct: async (
      productRequestDto: ProductRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'productRequestDto' is not null or undefined
      assertParamExists('addProduct', 'productRequestDto', productRequestDto)
      const localVarPath = `/storekeeper/products`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(productRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 입력한 아이디가 사용 가능한지 확인합니다.
     * @summary 점주 아이디 중복 확인
     * @param {string} adminId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkAdminId: async (adminId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'adminId' is not null or undefined
      assertParamExists('checkAdminId', 'adminId', adminId)
      const localVarPath = `/storekeeper/check-id`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (adminId !== undefined) {
        localVarQueryParameter['adminId'] = adminId
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 가게의 특정 주차 혜택을 삭제합니다.
     * @summary 주차 혜택 삭제
     * @param {number} benefitId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteParkingBenefit: async (benefitId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'benefitId' is not null or undefined
      assertParamExists('deleteParkingBenefit', 'benefitId', benefitId)
      const localVarPath = `/storekeeper/benefits/{benefitId}`.replace(
        `{${'benefitId'}}`,
        encodeURIComponent(String(benefitId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게의 특정 상품을 삭제합니다.
     * @summary 가게 상품 삭제
     * @param {number} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProduct: async (productId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'productId' is not null or undefined
      assertParamExists('deleteProduct', 'productId', productId)
      const localVarPath = `/storekeeper/products/{productId}`.replace(
        `{${'productId'}}`,
        encodeURIComponent(String(productId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게에 연계된 모든 주차장 목록을 조회합니다.
     * @summary 연계된 주차장 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAssociatedParkingLots: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/storekeeper/parking`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 점주의 가게 정보를 조회합니다.
     * @summary 내 가게 정보 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMyStoreInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/storekeeper/my-store`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게에 설정된 모든 주차 혜택(구매 금액별 할인)을 조회합니다.
     * @summary 주차 혜택 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingbenefits: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/storekeeper/benefits`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게에 등록된 모든 상품 목록을 조회합니다.
     * @summary 가게 상품 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProducts: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/storekeeper/products`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 주차장 코드를 사용하여 기존 주차장을 내 가게에 연결합니다.
     * @summary 주차장과 내 가게 연결
     * @param {LinkParkingRequestDto} linkParkingRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    linkParkingLot: async (
      linkParkingRequestDto: LinkParkingRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'linkParkingRequestDto' is not null or undefined
      assertParamExists('linkParkingLot', 'linkParkingRequestDto', linkParkingRequestDto)
      const localVarPath = `/storekeeper/parking/link`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(linkParkingRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 점주가 아이디와 비밀번호로 로그인하며, 심사 상태에 따라 결과가 달라집니다.
     * @summary 점주 로그인
     * @param {AdminLoginRequest} adminLoginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login: async (adminLoginRequest: AdminLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'adminLoginRequest' is not null or undefined
      assertParamExists('login', 'adminLoginRequest', adminLoginRequest)
      const localVarPath = `/storekeeper/login`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(adminLoginRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 가게 정보를 함께 받아 회원가입을 신청합니다.
     * @summary 점주 회원가입
     * @param {StorekeeperRegisterRequest} storekeeperRegisterRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerStorekeeper: async (
      storekeeperRegisterRequest: StorekeeperRegisterRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'storekeeperRegisterRequest' is not null or undefined
      assertParamExists('registerStorekeeper', 'storekeeperRegisterRequest', storekeeperRegisterRequest)
      const localVarPath = `/storekeeper/register`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        storekeeperRegisterRequest,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게에 연계된 주차장과의 연결을 끊습니다. (가게에 최소 1개의 주차장은 연결되어 있어야 합니다.)
     * @summary 가게와 주차장 연결 해제
     * @param {string} parkingCode
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlinkParkingLot: async (parkingCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'parkingCode' is not null or undefined
      assertParamExists('unlinkParkingLot', 'parkingCode', parkingCode)
      const localVarPath = `/storekeeper/parking/{parkingCode}/unlink`.replace(
        `{${'parkingCode'}}`,
        encodeURIComponent(String(parkingCode))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게에 연계된 주차장의 정보를 수정합니다.
     * @summary 연계된 주차장 정보 수정
     * @param {string} parkingCode
     * @param {ParkingLotManualRequestDto} parkingLotManualRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAssociatedParkingLot: async (
      parkingCode: string,
      parkingLotManualRequestDto: ParkingLotManualRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'parkingCode' is not null or undefined
      assertParamExists('updateAssociatedParkingLot', 'parkingCode', parkingCode)
      // verify required parameter 'parkingLotManualRequestDto' is not null or undefined
      assertParamExists('updateAssociatedParkingLot', 'parkingLotManualRequestDto', parkingLotManualRequestDto)
      const localVarPath = `/storekeeper/parking/{parkingCode}`.replace(
        `{${'parkingCode'}}`,
        encodeURIComponent(String(parkingCode))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        parkingLotManualRequestDto,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 점주의 가게 정보를 수정합니다.
     * @summary 내 가게 정보 수정
     * @param {MyStoreUpdateRequest} myStoreUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateMyStoreInfo: async (
      myStoreUpdateRequest: MyStoreUpdateRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'myStoreUpdateRequest' is not null or undefined
      assertParamExists('updateMyStoreInfo', 'myStoreUpdateRequest', myStoreUpdateRequest)
      const localVarPath = `/storekeeper/my-store`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(myStoreUpdateRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 기존 주차 혜택의 내용을 수정합니다.
     * @summary 주차 혜택 수정
     * @param {number} benefitId
     * @param {ParkingBenefitRequestDto} parkingBenefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateParkingBenefit: async (
      benefitId: number,
      parkingBenefitRequestDto: ParkingBenefitRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'benefitId' is not null or undefined
      assertParamExists('updateParkingBenefit', 'benefitId', benefitId)
      // verify required parameter 'parkingBenefitRequestDto' is not null or undefined
      assertParamExists('updateParkingBenefit', 'parkingBenefitRequestDto', parkingBenefitRequestDto)
      const localVarPath = `/storekeeper/benefits/{benefitId}`.replace(
        `{${'benefitId'}}`,
        encodeURIComponent(String(benefitId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        parkingBenefitRequestDto,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 내 가게의 특정 상품 정보를 수정합니다.
     * @summary 가게 상품 수정
     * @param {number} productId
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProduct: async (
      productId: number,
      productRequestDto: ProductRequestDto,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'productId' is not null or undefined
      assertParamExists('updateProduct', 'productId', productId)
      // verify required parameter 'productRequestDto' is not null or undefined
      assertParamExists('updateProduct', 'productRequestDto', productRequestDto)
      const localVarPath = `/storekeeper/products/{productId}`.replace(
        `{${'productId'}}`,
        encodeURIComponent(String(productId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(productRequestDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * StorekeeperApi - functional programming interface
 * @export
 */
export const StorekeeperApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = StorekeeperApiAxiosParamCreator(configuration)
  return {
    /**
     * 내 가게에 새로운 주차 혜택(구매 금액별 할인)을 추가합니다.
     * @summary 주차 혜택 추가
     * @param {ParkingBenefitRequestDto} parkingBenefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addParkingBenefit(
      parkingBenefitRequestDto: ParkingBenefitRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoParkingBenefitDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addParkingBenefit(parkingBenefitRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.addParkingBenefit']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게에 새로운 상품을 등록합니다.
     * @summary 가게 상품 추가
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async addProduct(
      productRequestDto: ProductRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoProductResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.addProduct(productRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.addProduct']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 입력한 아이디가 사용 가능한지 확인합니다.
     * @summary 점주 아이디 중복 확인
     * @param {string} adminId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async checkAdminId(
      adminId: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoBoolean>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.checkAdminId(adminId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.checkAdminId']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 가게의 특정 주차 혜택을 삭제합니다.
     * @summary 주차 혜택 삭제
     * @param {number} benefitId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteParkingBenefit(
      benefitId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteParkingBenefit(benefitId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.deleteParkingBenefit']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게의 특정 상품을 삭제합니다.
     * @summary 가게 상품 삭제
     * @param {number} productId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteProduct(
      productId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProduct(productId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.deleteProduct']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게에 연계된 모든 주차장 목록을 조회합니다.
     * @summary 연계된 주차장 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAssociatedParkingLots(
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListAssociatedParkingLotResponseDto>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAssociatedParkingLots(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.getAssociatedParkingLots']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 점주의 가게 정보를 조회합니다.
     * @summary 내 가게 정보 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getMyStoreInfo(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoMyStoreResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getMyStoreInfo(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.getMyStoreInfo']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게에 설정된 모든 주차 혜택(구매 금액별 할인)을 조회합니다.
     * @summary 주차 혜택 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getParkingbenefits(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListParkingBenefitDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getParkingbenefits(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.getParkingbenefits']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게에 등록된 모든 상품 목록을 조회합니다.
     * @summary 가게 상품 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getProducts(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListProductResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getProducts(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.getProducts']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 주차장 코드를 사용하여 기존 주차장을 내 가게에 연결합니다.
     * @summary 주차장과 내 가게 연결
     * @param {LinkParkingRequestDto} linkParkingRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async linkParkingLot(
      linkParkingRequestDto: LinkParkingRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.linkParkingLot(linkParkingRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.linkParkingLot']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 점주가 아이디와 비밀번호로 로그인하며, 심사 상태에 따라 결과가 달라집니다.
     * @summary 점주 로그인
     * @param {AdminLoginRequest} adminLoginRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async login(
      adminLoginRequest: AdminLoginRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoTokenResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.login(adminLoginRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.login']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 가게 정보를 함께 받아 회원가입을 신청합니다.
     * @summary 점주 회원가입
     * @param {StorekeeperRegisterRequest} storekeeperRegisterRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async registerStorekeeper(
      storekeeperRegisterRequest: StorekeeperRegisterRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.registerStorekeeper(storekeeperRegisterRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.registerStorekeeper']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게에 연계된 주차장과의 연결을 끊습니다. (가게에 최소 1개의 주차장은 연결되어 있어야 합니다.)
     * @summary 가게와 주차장 연결 해제
     * @param {string} parkingCode
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async unlinkParkingLot(
      parkingCode: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.unlinkParkingLot(parkingCode, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.unlinkParkingLot']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게에 연계된 주차장의 정보를 수정합니다.
     * @summary 연계된 주차장 정보 수정
     * @param {string} parkingCode
     * @param {ParkingLotManualRequestDto} parkingLotManualRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateAssociatedParkingLot(
      parkingCode: string,
      parkingLotManualRequestDto: ParkingLotManualRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateAssociatedParkingLot(
        parkingCode,
        parkingLotManualRequestDto,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.updateAssociatedParkingLot']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 점주의 가게 정보를 수정합니다.
     * @summary 내 가게 정보 수정
     * @param {MyStoreUpdateRequest} myStoreUpdateRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateMyStoreInfo(
      myStoreUpdateRequest: MyStoreUpdateRequest,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoMyStoreResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateMyStoreInfo(myStoreUpdateRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.updateMyStoreInfo']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 기존 주차 혜택의 내용을 수정합니다.
     * @summary 주차 혜택 수정
     * @param {number} benefitId
     * @param {ParkingBenefitRequestDto} parkingBenefitRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateParkingBenefit(
      benefitId: number,
      parkingBenefitRequestDto: ParkingBenefitRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoParkingBenefitDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateParkingBenefit(
        benefitId,
        parkingBenefitRequestDto,
        options
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.updateParkingBenefit']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 내 가게의 특정 상품 정보를 수정합니다.
     * @summary 가게 상품 수정
     * @param {number} productId
     * @param {ProductRequestDto} productRequestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateProduct(
      productId: number,
      productRequestDto: ProductRequestDto,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoProductResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateProduct(productId, productRequestDto, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['StorekeeperApi.updateProduct']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * StorekeeperApi - factory interface
 * @export
 */
export const StorekeeperApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = StorekeeperApiFp(configuration)
  return {
    /**
     * 내 가게에 새로운 주차 혜택(구매 금액별 할인)을 추가합니다.
     * @summary 주차 혜택 추가
     * @param {StorekeeperApiAddParkingBenefitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addParkingBenefit(
      requestParameters: StorekeeperApiAddParkingBenefitRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoParkingBenefitDto> {
      return localVarFp
        .addParkingBenefit(requestParameters.parkingBenefitRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 내 가게에 새로운 상품을 등록합니다.
     * @summary 가게 상품 추가
     * @param {StorekeeperApiAddProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addProduct(
      requestParameters: StorekeeperApiAddProductRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoProductResponseDto> {
      return localVarFp
        .addProduct(requestParameters.productRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 입력한 아이디가 사용 가능한지 확인합니다.
     * @summary 점주 아이디 중복 확인
     * @param {StorekeeperApiCheckAdminIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkAdminId(
      requestParameters: StorekeeperApiCheckAdminIdRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoBoolean> {
      return localVarFp.checkAdminId(requestParameters.adminId, options).then((request) => request(axios, basePath))
    },
    /**
     * 가게의 특정 주차 혜택을 삭제합니다.
     * @summary 주차 혜택 삭제
     * @param {StorekeeperApiDeleteParkingBenefitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteParkingBenefit(
      requestParameters: StorekeeperApiDeleteParkingBenefitRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .deleteParkingBenefit(requestParameters.benefitId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 내 가게의 특정 상품을 삭제합니다.
     * @summary 가게 상품 삭제
     * @param {StorekeeperApiDeleteProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteProduct(
      requestParameters: StorekeeperApiDeleteProductRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp.deleteProduct(requestParameters.productId, options).then((request) => request(axios, basePath))
    },
    /**
     * 내 가게에 연계된 모든 주차장 목록을 조회합니다.
     * @summary 연계된 주차장 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAssociatedParkingLots(
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoListAssociatedParkingLotResponseDto> {
      return localVarFp.getAssociatedParkingLots(options).then((request) => request(axios, basePath))
    },
    /**
     * 점주의 가게 정보를 조회합니다.
     * @summary 내 가게 정보 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMyStoreInfo(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoMyStoreResponse> {
      return localVarFp.getMyStoreInfo(options).then((request) => request(axios, basePath))
    },
    /**
     * 내 가게에 설정된 모든 주차 혜택(구매 금액별 할인)을 조회합니다.
     * @summary 주차 혜택 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingbenefits(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoListParkingBenefitDto> {
      return localVarFp.getParkingbenefits(options).then((request) => request(axios, basePath))
    },
    /**
     * 내 가게에 등록된 모든 상품 목록을 조회합니다.
     * @summary 가게 상품 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getProducts(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoListProductResponseDto> {
      return localVarFp.getProducts(options).then((request) => request(axios, basePath))
    },
    /**
     * 주차장 코드를 사용하여 기존 주차장을 내 가게에 연결합니다.
     * @summary 주차장과 내 가게 연결
     * @param {StorekeeperApiLinkParkingLotRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    linkParkingLot(
      requestParameters: StorekeeperApiLinkParkingLotRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .linkParkingLot(requestParameters.linkParkingRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 점주가 아이디와 비밀번호로 로그인하며, 심사 상태에 따라 결과가 달라집니다.
     * @summary 점주 로그인
     * @param {StorekeeperApiLoginRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    login(
      requestParameters: StorekeeperApiLoginRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoTokenResponse> {
      return localVarFp.login(requestParameters.adminLoginRequest, options).then((request) => request(axios, basePath))
    },
    /**
     * 가게 정보를 함께 받아 회원가입을 신청합니다.
     * @summary 점주 회원가입
     * @param {StorekeeperApiRegisterStorekeeperRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerStorekeeper(
      requestParameters: StorekeeperApiRegisterStorekeeperRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .registerStorekeeper(requestParameters.storekeeperRegisterRequest, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 내 가게에 연계된 주차장과의 연결을 끊습니다. (가게에 최소 1개의 주차장은 연결되어 있어야 합니다.)
     * @summary 가게와 주차장 연결 해제
     * @param {StorekeeperApiUnlinkParkingLotRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlinkParkingLot(
      requestParameters: StorekeeperApiUnlinkParkingLotRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .unlinkParkingLot(requestParameters.parkingCode, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 내 가게에 연계된 주차장의 정보를 수정합니다.
     * @summary 연계된 주차장 정보 수정
     * @param {StorekeeperApiUpdateAssociatedParkingLotRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAssociatedParkingLot(
      requestParameters: StorekeeperApiUpdateAssociatedParkingLotRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .updateAssociatedParkingLot(
          requestParameters.parkingCode,
          requestParameters.parkingLotManualRequestDto,
          options
        )
        .then((request) => request(axios, basePath))
    },
    /**
     * 점주의 가게 정보를 수정합니다.
     * @summary 내 가게 정보 수정
     * @param {StorekeeperApiUpdateMyStoreInfoRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateMyStoreInfo(
      requestParameters: StorekeeperApiUpdateMyStoreInfoRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoMyStoreResponse> {
      return localVarFp
        .updateMyStoreInfo(requestParameters.myStoreUpdateRequest, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 기존 주차 혜택의 내용을 수정합니다.
     * @summary 주차 혜택 수정
     * @param {StorekeeperApiUpdateParkingBenefitRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateParkingBenefit(
      requestParameters: StorekeeperApiUpdateParkingBenefitRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoParkingBenefitDto> {
      return localVarFp
        .updateParkingBenefit(requestParameters.benefitId, requestParameters.parkingBenefitRequestDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 내 가게의 특정 상품 정보를 수정합니다.
     * @summary 가게 상품 수정
     * @param {StorekeeperApiUpdateProductRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateProduct(
      requestParameters: StorekeeperApiUpdateProductRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoProductResponseDto> {
      return localVarFp
        .updateProduct(requestParameters.productId, requestParameters.productRequestDto, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for addParkingBenefit operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiAddParkingBenefitRequest
 */
export interface StorekeeperApiAddParkingBenefitRequest {
  /**
   *
   * @type {ParkingBenefitRequestDto}
   * @memberof StorekeeperApiAddParkingBenefit
   */
  readonly parkingBenefitRequestDto: ParkingBenefitRequestDto
}

/**
 * Request parameters for addProduct operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiAddProductRequest
 */
export interface StorekeeperApiAddProductRequest {
  /**
   *
   * @type {ProductRequestDto}
   * @memberof StorekeeperApiAddProduct
   */
  readonly productRequestDto: ProductRequestDto
}

/**
 * Request parameters for checkAdminId operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiCheckAdminIdRequest
 */
export interface StorekeeperApiCheckAdminIdRequest {
  /**
   *
   * @type {string}
   * @memberof StorekeeperApiCheckAdminId
   */
  readonly adminId: string
}

/**
 * Request parameters for deleteParkingBenefit operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiDeleteParkingBenefitRequest
 */
export interface StorekeeperApiDeleteParkingBenefitRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiDeleteParkingBenefit
   */
  readonly benefitId: number
}

/**
 * Request parameters for deleteProduct operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiDeleteProductRequest
 */
export interface StorekeeperApiDeleteProductRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiDeleteProduct
   */
  readonly productId: number
}

/**
 * Request parameters for linkParkingLot operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiLinkParkingLotRequest
 */
export interface StorekeeperApiLinkParkingLotRequest {
  /**
   *
   * @type {LinkParkingRequestDto}
   * @memberof StorekeeperApiLinkParkingLot
   */
  readonly linkParkingRequestDto: LinkParkingRequestDto
}

/**
 * Request parameters for login operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiLoginRequest
 */
export interface StorekeeperApiLoginRequest {
  /**
   *
   * @type {AdminLoginRequest}
   * @memberof StorekeeperApiLogin
   */
  readonly adminLoginRequest: AdminLoginRequest
}

/**
 * Request parameters for registerStorekeeper operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiRegisterStorekeeperRequest
 */
export interface StorekeeperApiRegisterStorekeeperRequest {
  /**
   *
   * @type {StorekeeperRegisterRequest}
   * @memberof StorekeeperApiRegisterStorekeeper
   */
  readonly storekeeperRegisterRequest: StorekeeperRegisterRequest
}

/**
 * Request parameters for unlinkParkingLot operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiUnlinkParkingLotRequest
 */
export interface StorekeeperApiUnlinkParkingLotRequest {
  /**
   *
   * @type {string}
   * @memberof StorekeeperApiUnlinkParkingLot
   */
  readonly parkingCode: string
}

/**
 * Request parameters for updateAssociatedParkingLot operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiUpdateAssociatedParkingLotRequest
 */
export interface StorekeeperApiUpdateAssociatedParkingLotRequest {
  /**
   *
   * @type {string}
   * @memberof StorekeeperApiUpdateAssociatedParkingLot
   */
  readonly parkingCode: string

  /**
   *
   * @type {ParkingLotManualRequestDto}
   * @memberof StorekeeperApiUpdateAssociatedParkingLot
   */
  readonly parkingLotManualRequestDto: ParkingLotManualRequestDto
}

/**
 * Request parameters for updateMyStoreInfo operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiUpdateMyStoreInfoRequest
 */
export interface StorekeeperApiUpdateMyStoreInfoRequest {
  /**
   *
   * @type {MyStoreUpdateRequest}
   * @memberof StorekeeperApiUpdateMyStoreInfo
   */
  readonly myStoreUpdateRequest: MyStoreUpdateRequest
}

/**
 * Request parameters for updateParkingBenefit operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiUpdateParkingBenefitRequest
 */
export interface StorekeeperApiUpdateParkingBenefitRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiUpdateParkingBenefit
   */
  readonly benefitId: number

  /**
   *
   * @type {ParkingBenefitRequestDto}
   * @memberof StorekeeperApiUpdateParkingBenefit
   */
  readonly parkingBenefitRequestDto: ParkingBenefitRequestDto
}

/**
 * Request parameters for updateProduct operation in StorekeeperApi.
 * @export
 * @interface StorekeeperApiUpdateProductRequest
 */
export interface StorekeeperApiUpdateProductRequest {
  /**
   *
   * @type {number}
   * @memberof StorekeeperApiUpdateProduct
   */
  readonly productId: number

  /**
   *
   * @type {ProductRequestDto}
   * @memberof StorekeeperApiUpdateProduct
   */
  readonly productRequestDto: ProductRequestDto
}

/**
 * StorekeeperApi - object-oriented interface
 * @export
 * @class StorekeeperApi
 * @extends {BaseAPI}
 */
export class StorekeeperApi extends BaseAPI {
  /**
   * 내 가게에 새로운 주차 혜택(구매 금액별 할인)을 추가합니다.
   * @summary 주차 혜택 추가
   * @param {StorekeeperApiAddParkingBenefitRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public addParkingBenefit(requestParameters: StorekeeperApiAddParkingBenefitRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .addParkingBenefit(requestParameters.parkingBenefitRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게에 새로운 상품을 등록합니다.
   * @summary 가게 상품 추가
   * @param {StorekeeperApiAddProductRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public addProduct(requestParameters: StorekeeperApiAddProductRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .addProduct(requestParameters.productRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 입력한 아이디가 사용 가능한지 확인합니다.
   * @summary 점주 아이디 중복 확인
   * @param {StorekeeperApiCheckAdminIdRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public checkAdminId(requestParameters: StorekeeperApiCheckAdminIdRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .checkAdminId(requestParameters.adminId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 가게의 특정 주차 혜택을 삭제합니다.
   * @summary 주차 혜택 삭제
   * @param {StorekeeperApiDeleteParkingBenefitRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public deleteParkingBenefit(
    requestParameters: StorekeeperApiDeleteParkingBenefitRequest,
    options?: RawAxiosRequestConfig
  ) {
    return StorekeeperApiFp(this.configuration)
      .deleteParkingBenefit(requestParameters.benefitId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게의 특정 상품을 삭제합니다.
   * @summary 가게 상품 삭제
   * @param {StorekeeperApiDeleteProductRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public deleteProduct(requestParameters: StorekeeperApiDeleteProductRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .deleteProduct(requestParameters.productId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게에 연계된 모든 주차장 목록을 조회합니다.
   * @summary 연계된 주차장 목록 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public getAssociatedParkingLots(options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .getAssociatedParkingLots(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 점주의 가게 정보를 조회합니다.
   * @summary 내 가게 정보 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public getMyStoreInfo(options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .getMyStoreInfo(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게에 설정된 모든 주차 혜택(구매 금액별 할인)을 조회합니다.
   * @summary 주차 혜택 목록 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public getParkingbenefits(options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .getParkingbenefits(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게에 등록된 모든 상품 목록을 조회합니다.
   * @summary 가게 상품 목록 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public getProducts(options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .getProducts(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 주차장 코드를 사용하여 기존 주차장을 내 가게에 연결합니다.
   * @summary 주차장과 내 가게 연결
   * @param {StorekeeperApiLinkParkingLotRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public linkParkingLot(requestParameters: StorekeeperApiLinkParkingLotRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .linkParkingLot(requestParameters.linkParkingRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 점주가 아이디와 비밀번호로 로그인하며, 심사 상태에 따라 결과가 달라집니다.
   * @summary 점주 로그인
   * @param {StorekeeperApiLoginRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public login(requestParameters: StorekeeperApiLoginRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .login(requestParameters.adminLoginRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 가게 정보를 함께 받아 회원가입을 신청합니다.
   * @summary 점주 회원가입
   * @param {StorekeeperApiRegisterStorekeeperRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public registerStorekeeper(
    requestParameters: StorekeeperApiRegisterStorekeeperRequest,
    options?: RawAxiosRequestConfig
  ) {
    return StorekeeperApiFp(this.configuration)
      .registerStorekeeper(requestParameters.storekeeperRegisterRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게에 연계된 주차장과의 연결을 끊습니다. (가게에 최소 1개의 주차장은 연결되어 있어야 합니다.)
   * @summary 가게와 주차장 연결 해제
   * @param {StorekeeperApiUnlinkParkingLotRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public unlinkParkingLot(requestParameters: StorekeeperApiUnlinkParkingLotRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .unlinkParkingLot(requestParameters.parkingCode, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게에 연계된 주차장의 정보를 수정합니다.
   * @summary 연계된 주차장 정보 수정
   * @param {StorekeeperApiUpdateAssociatedParkingLotRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public updateAssociatedParkingLot(
    requestParameters: StorekeeperApiUpdateAssociatedParkingLotRequest,
    options?: RawAxiosRequestConfig
  ) {
    return StorekeeperApiFp(this.configuration)
      .updateAssociatedParkingLot(requestParameters.parkingCode, requestParameters.parkingLotManualRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 점주의 가게 정보를 수정합니다.
   * @summary 내 가게 정보 수정
   * @param {StorekeeperApiUpdateMyStoreInfoRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public updateMyStoreInfo(requestParameters: StorekeeperApiUpdateMyStoreInfoRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .updateMyStoreInfo(requestParameters.myStoreUpdateRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 기존 주차 혜택의 내용을 수정합니다.
   * @summary 주차 혜택 수정
   * @param {StorekeeperApiUpdateParkingBenefitRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public updateParkingBenefit(
    requestParameters: StorekeeperApiUpdateParkingBenefitRequest,
    options?: RawAxiosRequestConfig
  ) {
    return StorekeeperApiFp(this.configuration)
      .updateParkingBenefit(requestParameters.benefitId, requestParameters.parkingBenefitRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 내 가게의 특정 상품 정보를 수정합니다.
   * @summary 가게 상품 수정
   * @param {StorekeeperApiUpdateProductRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof StorekeeperApi
   */
  public updateProduct(requestParameters: StorekeeperApiUpdateProductRequest, options?: RawAxiosRequestConfig) {
    return StorekeeperApiFp(this.configuration)
      .updateProduct(requestParameters.productId, requestParameters.productRequestDto, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
