/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { ResponseDtoListStoreOwnershipReqResponse } from '../models'
// @ts-ignore
import type { ResponseDtoUnit } from '../models'
/**
 * 관리자가게컨트롤러Api - axios parameter creator
 * @export
 */
export const 관리자가게컨트롤러ApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 관리자가 특정 소유권 신청을 승인 처리합니다.
     * @summary 소유권 신청 승인
     * @param {number} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    approveOwnershipRequest: async (requestId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'requestId' is not null or undefined
      assertParamExists('approveOwnershipRequest', 'requestId', requestId)
      const localVarPath = `/admin/store/ownership-requests/{requestId}/approve`.replace(
        `{${'requestId'}}`,
        encodeURIComponent(String(requestId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 관리자가 소유권 신청 목록을 조회합니다.
     * @summary 소유권 신청 목록 조회
     * @param {GetOwnershipRequestsStatusEnum} status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOwnershipRequests: async (
      status: GetOwnershipRequestsStatusEnum,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'status' is not null or undefined
      assertParamExists('getOwnershipRequests', 'status', status)
      const localVarPath = `/admin/store/ownership-requests`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (status !== undefined) {
        localVarQueryParameter['status'] = status
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 관리자가 특정 소유권 신청을 거절 처리합니다.
     * @summary 소유권 신청 거절
     * @param {number} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rejectOwnershipRequest: async (requestId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'requestId' is not null or undefined
      assertParamExists('rejectOwnershipRequest', 'requestId', requestId)
      const localVarPath = `/admin/store/ownership-requests/{requestId}/reject`.replace(
        `{${'requestId'}}`,
        encodeURIComponent(String(requestId))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * 관리자가게컨트롤러Api - functional programming interface
 * @export
 */
export const 관리자가게컨트롤러ApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = 관리자가게컨트롤러ApiAxiosParamCreator(configuration)
  return {
    /**
     * 관리자가 특정 소유권 신청을 승인 처리합니다.
     * @summary 소유권 신청 승인
     * @param {number} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async approveOwnershipRequest(
      requestId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.approveOwnershipRequest(requestId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['관리자가게컨트롤러Api.approveOwnershipRequest']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 관리자가 소유권 신청 목록을 조회합니다.
     * @summary 소유권 신청 목록 조회
     * @param {GetOwnershipRequestsStatusEnum} status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getOwnershipRequests(
      status: GetOwnershipRequestsStatusEnum,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoListStoreOwnershipReqResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getOwnershipRequests(status, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['관리자가게컨트롤러Api.getOwnershipRequests']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 관리자가 특정 소유권 신청을 거절 처리합니다.
     * @summary 소유권 신청 거절
     * @param {number} requestId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async rejectOwnershipRequest(
      requestId: number,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoUnit>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.rejectOwnershipRequest(requestId, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['관리자가게컨트롤러Api.rejectOwnershipRequest']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * 관리자가게컨트롤러Api - factory interface
 * @export
 */
export const 관리자가게컨트롤러ApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = 관리자가게컨트롤러ApiFp(configuration)
  return {
    /**
     * 관리자가 특정 소유권 신청을 승인 처리합니다.
     * @summary 소유권 신청 승인
     * @param {관리자가게컨트롤러ApiApproveOwnershipRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    approveOwnershipRequest(
      requestParameters: 관리자가게컨트롤러ApiApproveOwnershipRequestRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .approveOwnershipRequest(requestParameters.requestId, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 관리자가 소유권 신청 목록을 조회합니다.
     * @summary 소유권 신청 목록 조회
     * @param {관리자가게컨트롤러ApiGetOwnershipRequestsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOwnershipRequests(
      requestParameters: 관리자가게컨트롤러ApiGetOwnershipRequestsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoListStoreOwnershipReqResponse> {
      return localVarFp
        .getOwnershipRequests(requestParameters.status, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 관리자가 특정 소유권 신청을 거절 처리합니다.
     * @summary 소유권 신청 거절
     * @param {관리자가게컨트롤러ApiRejectOwnershipRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rejectOwnershipRequest(
      requestParameters: 관리자가게컨트롤러ApiRejectOwnershipRequestRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoUnit> {
      return localVarFp
        .rejectOwnershipRequest(requestParameters.requestId, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for approveOwnershipRequest operation in 관리자가게컨트롤러Api.
 * @export
 * @interface 관리자가게컨트롤러ApiApproveOwnershipRequestRequest
 */
export interface 관리자가게컨트롤러ApiApproveOwnershipRequestRequest {
  /**
   *
   * @type {number}
   * @memberof 관리자가게컨트롤러ApiApproveOwnershipRequest
   */
  readonly requestId: number
}

/**
 * Request parameters for getOwnershipRequests operation in 관리자가게컨트롤러Api.
 * @export
 * @interface 관리자가게컨트롤러ApiGetOwnershipRequestsRequest
 */
export interface 관리자가게컨트롤러ApiGetOwnershipRequestsRequest {
  /**
   *
   * @type {'PENDING' | 'APPROVED' | 'REJECTED'}
   * @memberof 관리자가게컨트롤러ApiGetOwnershipRequests
   */
  readonly status: GetOwnershipRequestsStatusEnum
}

/**
 * Request parameters for rejectOwnershipRequest operation in 관리자가게컨트롤러Api.
 * @export
 * @interface 관리자가게컨트롤러ApiRejectOwnershipRequestRequest
 */
export interface 관리자가게컨트롤러ApiRejectOwnershipRequestRequest {
  /**
   *
   * @type {number}
   * @memberof 관리자가게컨트롤러ApiRejectOwnershipRequest
   */
  readonly requestId: number
}

/**
 * 관리자가게컨트롤러Api - object-oriented interface
 * @export
 * @class 관리자가게컨트롤러Api
 * @extends {BaseAPI}
 */
export class 관리자가게컨트롤러Api extends BaseAPI {
  /**
   * 관리자가 특정 소유권 신청을 승인 처리합니다.
   * @summary 소유권 신청 승인
   * @param {관리자가게컨트롤러ApiApproveOwnershipRequestRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof 관리자가게컨트롤러Api
   */
  public approveOwnershipRequest(
    requestParameters: 관리자가게컨트롤러ApiApproveOwnershipRequestRequest,
    options?: RawAxiosRequestConfig
  ) {
    return 관리자가게컨트롤러ApiFp(this.configuration)
      .approveOwnershipRequest(requestParameters.requestId, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 관리자가 소유권 신청 목록을 조회합니다.
   * @summary 소유권 신청 목록 조회
   * @param {관리자가게컨트롤러ApiGetOwnershipRequestsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof 관리자가게컨트롤러Api
   */
  public getOwnershipRequests(
    requestParameters: 관리자가게컨트롤러ApiGetOwnershipRequestsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return 관리자가게컨트롤러ApiFp(this.configuration)
      .getOwnershipRequests(requestParameters.status, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 관리자가 특정 소유권 신청을 거절 처리합니다.
   * @summary 소유권 신청 거절
   * @param {관리자가게컨트롤러ApiRejectOwnershipRequestRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof 관리자가게컨트롤러Api
   */
  public rejectOwnershipRequest(
    requestParameters: 관리자가게컨트롤러ApiRejectOwnershipRequestRequest,
    options?: RawAxiosRequestConfig
  ) {
    return 관리자가게컨트롤러ApiFp(this.configuration)
      .rejectOwnershipRequest(requestParameters.requestId, options)
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * @export
 */
export const GetOwnershipRequestsStatusEnum = {
  Pending: 'PENDING',
  Approved: 'APPROVED',
  Rejected: 'REJECTED',
} as const
export type GetOwnershipRequestsStatusEnum =
  (typeof GetOwnershipRequestsStatusEnum)[keyof typeof GetOwnershipRequestsStatusEnum]
