/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { ParkingLotSearchRequest } from '../models'
// @ts-ignore
import type { ResponseDtoPageResponseParkingLotListResponse } from '../models'
// @ts-ignore
import type { ResponseDtoParkingLotDetailResponse } from '../models'
/**
 * 주차장컨트롤러Api - axios parameter creator
 * @export
 */
export const 주차장컨트롤러ApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 주차장 상세 정보를 조회하는 API입니다.
     * @summary 주차장 상세 정보 조회
     * @param {string} parkingCode
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingLotDetail: async (parkingCode: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'parkingCode' is not null or undefined
      assertParamExists('getParkingLotDetail', 'parkingCode', parkingCode)
      const localVarPath = `/parking/detail/{parkingCode}`.replace(
        `{${'parkingCode'}}`,
        encodeURIComponent(String(parkingCode))
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 지도에서 주차장을 검색하는 API입니다.
     * @summary 지도 기반 주차장 검색
     * @param {ParkingLotSearchRequest} parkingLotSearchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchParkingLots: async (
      parkingLotSearchRequest: ParkingLotSearchRequest,
      options: RawAxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'parkingLotSearchRequest' is not null or undefined
      assertParamExists('searchParkingLots', 'parkingLotSearchRequest', parkingLotSearchRequest)
      const localVarPath = `/parking/map/search`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        parkingLotSearchRequest,
        localVarRequestOptions,
        configuration
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * 주차장컨트롤러Api - functional programming interface
 * @export
 */
export const 주차장컨트롤러ApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = 주차장컨트롤러ApiAxiosParamCreator(configuration)
  return {
    /**
     * 주차장 상세 정보를 조회하는 API입니다.
     * @summary 주차장 상세 정보 조회
     * @param {string} parkingCode
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getParkingLotDetail(
      parkingCode: string,
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoParkingLotDetailResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getParkingLotDetail(parkingCode, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['주차장컨트롤러Api.getParkingLotDetail']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 지도에서 주차장을 검색하는 API입니다.
     * @summary 지도 기반 주차장 검색
     * @param {ParkingLotSearchRequest} parkingLotSearchRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchParkingLots(
      parkingLotSearchRequest: ParkingLotSearchRequest,
      options?: RawAxiosRequestConfig
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoPageResponseParkingLotListResponse>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.searchParkingLots(parkingLotSearchRequest, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['주차장컨트롤러Api.searchParkingLots']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * 주차장컨트롤러Api - factory interface
 * @export
 */
export const 주차장컨트롤러ApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = 주차장컨트롤러ApiFp(configuration)
  return {
    /**
     * 주차장 상세 정보를 조회하는 API입니다.
     * @summary 주차장 상세 정보 조회
     * @param {주차장컨트롤러ApiGetParkingLotDetailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getParkingLotDetail(
      requestParameters: 주차장컨트롤러ApiGetParkingLotDetailRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoParkingLotDetailResponse> {
      return localVarFp
        .getParkingLotDetail(requestParameters.parkingCode, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * 지도에서 주차장을 검색하는 API입니다.
     * @summary 지도 기반 주차장 검색
     * @param {주차장컨트롤러ApiSearchParkingLotsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchParkingLots(
      requestParameters: 주차장컨트롤러ApiSearchParkingLotsRequest,
      options?: RawAxiosRequestConfig
    ): AxiosPromise<ResponseDtoPageResponseParkingLotListResponse> {
      return localVarFp
        .searchParkingLots(requestParameters.parkingLotSearchRequest, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for getParkingLotDetail operation in 주차장컨트롤러Api.
 * @export
 * @interface 주차장컨트롤러ApiGetParkingLotDetailRequest
 */
export interface 주차장컨트롤러ApiGetParkingLotDetailRequest {
  /**
   *
   * @type {string}
   * @memberof 주차장컨트롤러ApiGetParkingLotDetail
   */
  readonly parkingCode: string
}

/**
 * Request parameters for searchParkingLots operation in 주차장컨트롤러Api.
 * @export
 * @interface 주차장컨트롤러ApiSearchParkingLotsRequest
 */
export interface 주차장컨트롤러ApiSearchParkingLotsRequest {
  /**
   *
   * @type {ParkingLotSearchRequest}
   * @memberof 주차장컨트롤러ApiSearchParkingLots
   */
  readonly parkingLotSearchRequest: ParkingLotSearchRequest
}

/**
 * 주차장컨트롤러Api - object-oriented interface
 * @export
 * @class 주차장컨트롤러Api
 * @extends {BaseAPI}
 */
export class 주차장컨트롤러Api extends BaseAPI {
  /**
   * 주차장 상세 정보를 조회하는 API입니다.
   * @summary 주차장 상세 정보 조회
   * @param {주차장컨트롤러ApiGetParkingLotDetailRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof 주차장컨트롤러Api
   */
  public getParkingLotDetail(
    requestParameters: 주차장컨트롤러ApiGetParkingLotDetailRequest,
    options?: RawAxiosRequestConfig
  ) {
    return 주차장컨트롤러ApiFp(this.configuration)
      .getParkingLotDetail(requestParameters.parkingCode, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 지도에서 주차장을 검색하는 API입니다.
   * @summary 지도 기반 주차장 검색
   * @param {주차장컨트롤러ApiSearchParkingLotsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof 주차장컨트롤러Api
   */
  public searchParkingLots(
    requestParameters: 주차장컨트롤러ApiSearchParkingLotsRequest,
    options?: RawAxiosRequestConfig
  ) {
    return 주차장컨트롤러ApiFp(this.configuration)
      .searchParkingLots(requestParameters.parkingLotSearchRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
