/* tslint:disable */
/* eslint-disable */
/**
 * Local Parking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { ResponseDtoCategoryResponse } from '../models'
/**
 * 카테고리컨트롤러Api - axios parameter creator
 * @export
 */
export const 카테고리컨트롤러ApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * 상위 카테고리를 조회하는 API입니다.
     * @summary 상위 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/category/parent`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * 전체 카테고리를 조회하는 API입니다.
     * @summary 전체 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChildCategories: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/category/all`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer Token required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * 카테고리컨트롤러Api - functional programming interface
 * @export
 */
export const 카테고리컨트롤러ApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = 카테고리컨트롤러ApiAxiosParamCreator(configuration)
  return {
    /**
     * 상위 카테고리를 조회하는 API입니다.
     * @summary 상위 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getCategories(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoCategoryResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getCategories(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['카테고리컨트롤러Api.getCategories']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * 전체 카테고리를 조회하는 API입니다.
     * @summary 전체 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getChildCategories(
      options?: RawAxiosRequestConfig
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseDtoCategoryResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getChildCategories(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['카테고리컨트롤러Api.getChildCategories']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * 카테고리컨트롤러Api - factory interface
 * @export
 */
export const 카테고리컨트롤러ApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = 카테고리컨트롤러ApiFp(configuration)
  return {
    /**
     * 상위 카테고리를 조회하는 API입니다.
     * @summary 상위 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCategories(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoCategoryResponse> {
      return localVarFp.getCategories(options).then((request) => request(axios, basePath))
    },
    /**
     * 전체 카테고리를 조회하는 API입니다.
     * @summary 전체 카테고리 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getChildCategories(options?: RawAxiosRequestConfig): AxiosPromise<ResponseDtoCategoryResponse> {
      return localVarFp.getChildCategories(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * 카테고리컨트롤러Api - object-oriented interface
 * @export
 * @class 카테고리컨트롤러Api
 * @extends {BaseAPI}
 */
export class 카테고리컨트롤러Api extends BaseAPI {
  /**
   * 상위 카테고리를 조회하는 API입니다.
   * @summary 상위 카테고리 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof 카테고리컨트롤러Api
   */
  public getCategories(options?: RawAxiosRequestConfig) {
    return 카테고리컨트롤러ApiFp(this.configuration)
      .getCategories(options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * 전체 카테고리를 조회하는 API입니다.
   * @summary 전체 카테고리 조회
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof 카테고리컨트롤러Api
   */
  public getChildCategories(options?: RawAxiosRequestConfig) {
    return 카테고리컨트롤러ApiFp(this.configuration)
      .getChildCategories(options)
      .then((request) => request(this.axios, this.basePath))
  }
}
