/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as OnboardingLayoutImport } from './app/onboarding/layout'
import { Route as MapLayoutImport } from './app/map/layout'
import { Route as PageImport } from './app/page'
import { Route as MapPageImport } from './app/map/page'
import { Route as LoginPageImport } from './app/login/page'
import { Route as OnboardingTermsPageImport } from './app/onboarding/terms/page'
import { Route as OnboardingLandingPageImport } from './app/onboarding/landing/page'
import { Route as OnboardingFinalOnboardingPageImport } from './app/onboarding/final-onboarding/page'
import { Route as LoginSuccessPageImport } from './app/login/success/page'
import { Route as OnboardingTermsDetailPageImport } from './app/onboarding/terms/detail/page'

// Create/Update Routes

const OnboardingLayoutRoute = OnboardingLayoutImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const MapLayoutRoute = MapLayoutImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MapPageRoute = MapPageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MapLayoutRoute,
} as any)

const LoginPageRoute = LoginPageImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingTermsPageRoute = OnboardingTermsPageImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingLandingPageRoute = OnboardingLandingPageImport.update({
  id: '/landing/',
  path: '/landing/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

const OnboardingFinalOnboardingPageRoute =
  OnboardingFinalOnboardingPageImport.update({
    id: '/final-onboarding/',
    path: '/final-onboarding/',
    getParentRoute: () => OnboardingLayoutRoute,
  } as any)

const LoginSuccessPageRoute = LoginSuccessPageImport.update({
  id: '/login/success/',
  path: '/login/success/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingTermsDetailPageRoute = OnboardingTermsDetailPageImport.update({
  id: '/terms/detail/',
  path: '/terms/detail/',
  getParentRoute: () => OnboardingLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapLayoutImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginPageImport
      parentRoute: typeof rootRoute
    }
    '/map/': {
      id: '/map/'
      path: '/'
      fullPath: '/map/'
      preLoaderRoute: typeof MapPageImport
      parentRoute: typeof MapLayoutImport
    }
    '/login/success/': {
      id: '/login/success/'
      path: '/login/success'
      fullPath: '/login/success'
      preLoaderRoute: typeof LoginSuccessPageImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/final-onboarding/': {
      id: '/onboarding/final-onboarding/'
      path: '/final-onboarding'
      fullPath: '/onboarding/final-onboarding'
      preLoaderRoute: typeof OnboardingFinalOnboardingPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/landing/': {
      id: '/onboarding/landing/'
      path: '/landing'
      fullPath: '/onboarding/landing'
      preLoaderRoute: typeof OnboardingLandingPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/terms/': {
      id: '/onboarding/terms/'
      path: '/terms'
      fullPath: '/onboarding/terms'
      preLoaderRoute: typeof OnboardingTermsPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
    '/onboarding/terms/detail/': {
      id: '/onboarding/terms/detail/'
      path: '/terms/detail'
      fullPath: '/onboarding/terms/detail'
      preLoaderRoute: typeof OnboardingTermsDetailPageImport
      parentRoute: typeof OnboardingLayoutImport
    }
  }
}

// Create and export the route tree

interface MapLayoutRouteChildren {
  MapPageRoute: typeof MapPageRoute
}

const MapLayoutRouteChildren: MapLayoutRouteChildren = {
  MapPageRoute: MapPageRoute,
}

const MapLayoutRouteWithChildren = MapLayoutRoute._addFileChildren(
  MapLayoutRouteChildren,
)

interface OnboardingLayoutRouteChildren {
  OnboardingFinalOnboardingPageRoute: typeof OnboardingFinalOnboardingPageRoute
  OnboardingLandingPageRoute: typeof OnboardingLandingPageRoute
  OnboardingTermsPageRoute: typeof OnboardingTermsPageRoute
  OnboardingTermsDetailPageRoute: typeof OnboardingTermsDetailPageRoute
}

const OnboardingLayoutRouteChildren: OnboardingLayoutRouteChildren = {
  OnboardingFinalOnboardingPageRoute: OnboardingFinalOnboardingPageRoute,
  OnboardingLandingPageRoute: OnboardingLandingPageRoute,
  OnboardingTermsPageRoute: OnboardingTermsPageRoute,
  OnboardingTermsDetailPageRoute: OnboardingTermsDetailPageRoute,
}

const OnboardingLayoutRouteWithChildren =
  OnboardingLayoutRoute._addFileChildren(OnboardingLayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/map': typeof MapLayoutRouteWithChildren
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/login': typeof LoginPageRoute
  '/map/': typeof MapPageRoute
  '/login/success': typeof LoginSuccessPageRoute
  '/onboarding/final-onboarding': typeof OnboardingFinalOnboardingPageRoute
  '/onboarding/landing': typeof OnboardingLandingPageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/onboarding/terms/detail': typeof OnboardingTermsDetailPageRoute
}

export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/login': typeof LoginPageRoute
  '/map': typeof MapPageRoute
  '/login/success': typeof LoginSuccessPageRoute
  '/onboarding/final-onboarding': typeof OnboardingFinalOnboardingPageRoute
  '/onboarding/landing': typeof OnboardingLandingPageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/onboarding/terms/detail': typeof OnboardingTermsDetailPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof PageRoute
  '/map': typeof MapLayoutRouteWithChildren
  '/onboarding': typeof OnboardingLayoutRouteWithChildren
  '/login/': typeof LoginPageRoute
  '/map/': typeof MapPageRoute
  '/login/success/': typeof LoginSuccessPageRoute
  '/onboarding/final-onboarding/': typeof OnboardingFinalOnboardingPageRoute
  '/onboarding/landing/': typeof OnboardingLandingPageRoute
  '/onboarding/terms/': typeof OnboardingTermsPageRoute
  '/onboarding/terms/detail/': typeof OnboardingTermsDetailPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/onboarding'
    | '/login'
    | '/map/'
    | '/login/success'
    | '/onboarding/final-onboarding'
    | '/onboarding/landing'
    | '/onboarding/terms'
    | '/onboarding/terms/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/map'
    | '/login/success'
    | '/onboarding/final-onboarding'
    | '/onboarding/landing'
    | '/onboarding/terms'
    | '/onboarding/terms/detail'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/onboarding'
    | '/login/'
    | '/map/'
    | '/login/success/'
    | '/onboarding/final-onboarding/'
    | '/onboarding/landing/'
    | '/onboarding/terms/'
    | '/onboarding/terms/detail/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  MapLayoutRoute: typeof MapLayoutRouteWithChildren
  OnboardingLayoutRoute: typeof OnboardingLayoutRouteWithChildren
  LoginPageRoute: typeof LoginPageRoute
  LoginSuccessPageRoute: typeof LoginSuccessPageRoute
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  MapLayoutRoute: MapLayoutRouteWithChildren,
  OnboardingLayoutRoute: OnboardingLayoutRouteWithChildren,
  LoginPageRoute: LoginPageRoute,
  LoginSuccessPageRoute: LoginSuccessPageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/map",
        "/onboarding",
        "/login/",
        "/login/success/"
      ]
    },
    "/": {
      "filePath": "page.tsx"
    },
    "/map": {
      "filePath": "map/layout.tsx",
      "children": [
        "/map/"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding/layout.tsx",
      "children": [
        "/onboarding/final-onboarding/",
        "/onboarding/landing/",
        "/onboarding/terms/",
        "/onboarding/terms/detail/"
      ]
    },
    "/login/": {
      "filePath": "login/page.tsx"
    },
    "/map/": {
      "filePath": "map/page.tsx",
      "parent": "/map"
    },
    "/login/success/": {
      "filePath": "login/success/page.tsx"
    },
    "/onboarding/final-onboarding/": {
      "filePath": "onboarding/final-onboarding/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/landing/": {
      "filePath": "onboarding/landing/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/terms/": {
      "filePath": "onboarding/terms/page.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/terms/detail/": {
      "filePath": "onboarding/terms/detail/page.tsx",
      "parent": "/onboarding"
    }
  }
}
ROUTE_MANIFEST_END */
