/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as PageImport } from './app/page'
import { Route as MapPageImport } from './app/map/page'
import { Route as OnboardingTermsPageImport } from './app/onboarding/terms/page'
import { Route as OnboardingLandingPageImport } from './app/onboarding/landing/page'
import { Route as OnboardingFinalOnboardingPageImport } from './app/onboarding/final-onboarding/page'
import { Route as authLoginPageImport } from './app/(auth)/login/page'
import { Route as authLoginSuccessPageImport } from './app/(auth)/login/success/page'

// Create/Update Routes

const PageRoute = PageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MapPageRoute = MapPageImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingTermsPageRoute = OnboardingTermsPageImport.update({
  id: '/onboarding/terms/',
  path: '/onboarding/terms/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingLandingPageRoute = OnboardingLandingPageImport.update({
  id: '/onboarding/landing/',
  path: '/onboarding/landing/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingFinalOnboardingPageRoute =
  OnboardingFinalOnboardingPageImport.update({
    id: '/onboarding/final-onboarding/',
    path: '/onboarding/final-onboarding/',
    getParentRoute: () => rootRoute,
  } as any)

const authLoginPageRoute = authLoginPageImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginSuccessPageRoute = authLoginSuccessPageImport.update({
  id: '/(auth)/login/success/',
  path: '/login/success/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapPageImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginPageImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/final-onboarding/': {
      id: '/onboarding/final-onboarding/'
      path: '/onboarding/final-onboarding'
      fullPath: '/onboarding/final-onboarding'
      preLoaderRoute: typeof OnboardingFinalOnboardingPageImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/landing/': {
      id: '/onboarding/landing/'
      path: '/onboarding/landing'
      fullPath: '/onboarding/landing'
      preLoaderRoute: typeof OnboardingLandingPageImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/terms/': {
      id: '/onboarding/terms/'
      path: '/onboarding/terms'
      fullPath: '/onboarding/terms'
      preLoaderRoute: typeof OnboardingTermsPageImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/success/': {
      id: '/(auth)/login/success/'
      path: '/login/success'
      fullPath: '/login/success'
      preLoaderRoute: typeof authLoginSuccessPageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/map': typeof MapPageRoute
  '/login': typeof authLoginPageRoute
  '/onboarding/final-onboarding': typeof OnboardingFinalOnboardingPageRoute
  '/onboarding/landing': typeof OnboardingLandingPageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/login/success': typeof authLoginSuccessPageRoute
}

export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/map': typeof MapPageRoute
  '/login': typeof authLoginPageRoute
  '/onboarding/final-onboarding': typeof OnboardingFinalOnboardingPageRoute
  '/onboarding/landing': typeof OnboardingLandingPageRoute
  '/onboarding/terms': typeof OnboardingTermsPageRoute
  '/login/success': typeof authLoginSuccessPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof PageRoute
  '/map/': typeof MapPageRoute
  '/(auth)/login/': typeof authLoginPageRoute
  '/onboarding/final-onboarding/': typeof OnboardingFinalOnboardingPageRoute
  '/onboarding/landing/': typeof OnboardingLandingPageRoute
  '/onboarding/terms/': typeof OnboardingTermsPageRoute
  '/(auth)/login/success/': typeof authLoginSuccessPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/login'
    | '/onboarding/final-onboarding'
    | '/onboarding/landing'
    | '/onboarding/terms'
    | '/login/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/login'
    | '/onboarding/final-onboarding'
    | '/onboarding/landing'
    | '/onboarding/terms'
    | '/login/success'
  id:
    | '__root__'
    | '/'
    | '/map/'
    | '/(auth)/login/'
    | '/onboarding/final-onboarding/'
    | '/onboarding/landing/'
    | '/onboarding/terms/'
    | '/(auth)/login/success/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  MapPageRoute: typeof MapPageRoute
  authLoginPageRoute: typeof authLoginPageRoute
  OnboardingFinalOnboardingPageRoute: typeof OnboardingFinalOnboardingPageRoute
  OnboardingLandingPageRoute: typeof OnboardingLandingPageRoute
  OnboardingTermsPageRoute: typeof OnboardingTermsPageRoute
  authLoginSuccessPageRoute: typeof authLoginSuccessPageRoute
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  MapPageRoute: MapPageRoute,
  authLoginPageRoute: authLoginPageRoute,
  OnboardingFinalOnboardingPageRoute: OnboardingFinalOnboardingPageRoute,
  OnboardingLandingPageRoute: OnboardingLandingPageRoute,
  OnboardingTermsPageRoute: OnboardingTermsPageRoute,
  authLoginSuccessPageRoute: authLoginSuccessPageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/map/",
        "/(auth)/login/",
        "/onboarding/final-onboarding/",
        "/onboarding/landing/",
        "/onboarding/terms/",
        "/(auth)/login/success/"
      ]
    },
    "/": {
      "filePath": "page.tsx"
    },
    "/map/": {
      "filePath": "map/page.tsx"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/page.tsx"
    },
    "/onboarding/final-onboarding/": {
      "filePath": "onboarding/final-onboarding/page.tsx"
    },
    "/onboarding/landing/": {
      "filePath": "onboarding/landing/page.tsx"
    },
    "/onboarding/terms/": {
      "filePath": "onboarding/terms/page.tsx"
    },
    "/(auth)/login/success/": {
      "filePath": "(auth)/login/success/page.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
